# Copyright 2020 The XLS Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# proto-file: xls/estimators/estimator_model.proto
# proto-message: xls.estimator_model.EstimatorModel

# Dummy "unit" model for testing. All operations have unit latency (1ps).
op_models { op: "kAdd" estimator { fixed: 1 } }
op_models { op: "kAnd" estimator { fixed: 1 } }
op_models { op: "kAndReduce" estimator { fixed: 1 } }
op_models { op: "kArray" estimator { fixed: 1 } }
op_models { op: "kArrayConcat" estimator { fixed: 1 } }
op_models { op: "kArrayIndex" estimator { fixed: 1 } }
op_models { op: "kArraySlice" estimator { fixed: 1 } }
op_models { op: "kArrayUpdate" estimator { fixed: 1 } }
op_models { op: "kBitSlice" estimator { fixed: 1 } }
op_models { op: "kBitSliceUpdate" estimator { fixed: 1 } }
op_models { op: "kConcat" estimator { fixed: 1 } }
op_models { op: "kCountedFor" estimator { fixed: 1 } }
op_models { op: "kDecode" estimator { fixed: 1 } }
op_models { op: "kDynamicBitSlice" estimator { fixed: 1 } }
op_models { op: "kDynamicCountedFor" estimator { fixed: 1 } }
op_models { op: "kEncode" estimator { fixed: 1 } }
op_models { op: "kEq" estimator { fixed: 1 } }
op_models { op: "kGate" estimator { fixed: 1 } }
op_models { op: "kIdentity" estimator { fixed: 1 } }
op_models { op: "kInstantiationInput" estimator { fixed: 1 } }
op_models { op: "kInstantiationOutput" estimator { fixed: 1 } }
op_models { op: "kInvoke" estimator { fixed: 1 } }
op_models { op: "kMap" estimator { fixed: 1 } }
op_models { op: "kNand" estimator { fixed: 1 } }
op_models { op: "kNe" estimator { fixed: 1 } }
op_models { op: "kNeg" estimator { fixed: 1 } }
op_models { op: "kNor" estimator { fixed: 1 } }
op_models { op: "kNot" estimator { fixed: 1 } }
op_models { op: "kOneHot" estimator { fixed: 1 } }
op_models { op: "kOneHotSel" estimator { fixed: 1 } }
op_models { op: "kPrioritySel" estimator { fixed: 1 } }
op_models { op: "kOr" estimator { fixed: 1 } }
op_models { op: "kOrReduce" estimator { fixed: 1 } }
op_models { op: "kReceive" estimator { fixed: 1 } }
op_models { op: "kReverse" estimator { fixed: 1 } }
op_models { op: "kSDiv" estimator { fixed: 1 } }
op_models { op: "kSGe" estimator { fixed: 1 } }
op_models { op: "kSGt" estimator { fixed: 1 } }
op_models { op: "kSLe" estimator { fixed: 1 } }
op_models { op: "kSLt" estimator { fixed: 1 } }
op_models { op: "kSMod" estimator { fixed: 1 } }
op_models { op: "kSMul" estimator { fixed: 1 } }
op_models { op: "kSMulp" estimator { fixed: 1 } }
op_models { op: "kSel" estimator { fixed: 1 } }
op_models { op: "kSend" estimator { fixed: 1 } }
op_models { op: "kShll" estimator { fixed: 1 } }
op_models { op: "kShra" estimator { fixed: 1 } }
op_models { op: "kShrl" estimator { fixed: 1 } }
op_models { op: "kSignExt" estimator { fixed: 1 } }
op_models { op: "kSub" estimator { fixed: 1 } }
op_models { op: "kTrace" estimator { fixed: 1 } }
op_models { op: "kTuple" estimator { fixed: 1 } }
op_models { op: "kTupleIndex" estimator { fixed: 1 } }
op_models { op: "kUDiv" estimator { fixed: 1 } }
op_models { op: "kUGe" estimator { fixed: 1 } }
op_models { op: "kUGt" estimator { fixed: 1 } }
op_models { op: "kULe" estimator { fixed: 1 } }
op_models { op: "kULt" estimator { fixed: 1 } }
op_models { op: "kUMod" estimator { fixed: 1 } }
op_models { op: "kUMul" estimator { fixed: 1 } }
op_models { op: "kUMulp" estimator { fixed: 1 } }
op_models { op: "kXor" estimator { fixed: 1 } }
op_models { op: "kXorReduce" estimator { fixed: 1 } }
op_models { op: "kZeroExt" estimator { fixed: 1 } }

# Always-free ops.
op_models { op: "kParam" estimator { fixed: 0 } }
op_models { op: "kStateRead" estimator { fixed: 0 } }
op_models { op: "kNext" estimator { fixed: 0 } }
op_models { op: "kAfterAll" estimator { fixed: 0 } }
op_models { op: "kMinDelay" estimator { fixed: 0 } }
op_models { op: "kAssert" estimator { fixed: 0 } }
op_models { op: "kCover" estimator { fixed: 0 } }
op_models { op: "kInputPort" estimator { fixed: 0 } }
op_models { op: "kOutputPort" estimator { fixed: 0 } }
op_models { op: "kRegisterRead" estimator { fixed: 0 } }
op_models { op: "kRegisterWrite" estimator { fixed: 0 } }
op_models { op: "kLiteral" estimator { fixed: 0 } }

metric: AREA_METRIC
