// Copyright 2021 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests the IR output generated by DSLX compound types (structs, tuples,
// arrays) and slicing operations. The IR is not checked for validity; it is
// only tested against a pre-constructed golden file.

#include <string>
#include <string_view>

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/status/status_matchers.h"
#include "xls/common/status/matchers.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/ir_convert/test_utils.h"
#include "xls/dslx/type_system/typecheck_test_utils.h"

namespace xls::dslx {
namespace {

using ::absl_testing::StatusIs;
using ::testing::HasSubstr;

TEST_F(IrConverterTest, Struct) {
  constexpr std::string_view program =
      R"(struct S {
  zub: u8,
  qux: u8,
}

fn f(a: S, b: S) -> u8 {
  let foo = a.zub + b.qux;
  (S { zub: u8:42, qux: u8:0 }).zub + (S { zub: u8:22, qux: u8:11 }).zub
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, Index) {
  constexpr std::string_view program =
      R"(fn f(x: uN[32][4]) -> u32 {
  x[u32:0]
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, TupleOfParameters) {
  constexpr std::string_view program =
      R"(fn f(x: u8, y: u8) -> (u8, u8) {
  (x, y)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, TupleOfLiterals) {
  constexpr std::string_view program =
      R"(fn f() -> (u8, u8) {
  (u8:0xaa, u8:0x55)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, TupleIndex) {
  constexpr std::string_view program =
      R"(fn main() -> u8 {
  let t = (u32:3, u8:4);
  t.1
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, BasicStruct) {
  constexpr std::string_view program =
      R"(
struct Point {
  x: u32,
  y: u32,
}

fn f(xy: u32) -> Point {
  Point { x: xy, y: xy }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, EnumUse) {
  constexpr std::string_view program =
      R"(
enum Foo : u32 {
  THING = 0,
  OTHER = 1,
}
fn f(x: Foo) -> Foo {
  if x == Foo::THING { Foo::OTHER } else { Foo::THING }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ArrayEllipsis) {
  constexpr std::string_view program =
      R"(
fn main() -> u8[2] {
  u8[2]:[0, ...]
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NonConstArrayEllipsis) {
  constexpr std::string_view program =
      R"(
fn main(x: bits[8]) -> u8[4] {
  u8[4]:[u8:0, x, ...]
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ArrayUpdate) {
  constexpr std::string_view program =
      R"(
fn main(input: u8[2]) -> u8[2] {
  update(input, u32:1, u8:0x42)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ArrayEnumerate) {
  constexpr std::string_view program = R"(
import std;
fn main(array: u8[4]) -> (u32, u8)[4] {
  std::enumerate(array)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "main"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SplatStructInstance) {
  constexpr std::string_view program =
      R"(
struct Point {
  x: u32,
  y: u32,
}

fn f(p: Point, new_y: u32) -> Point {
  Point { y: new_y, ..p }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, WidthSlice) {
  constexpr std::string_view program =
      R"(
fn f(x: u32, y: u32) -> u8 {
  x[2+:u8]+x[y+:u8]
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SingleElementBitsArrayParam) {
  constexpr std::string_view program =
      R"(
fn f(x: u32[1]) -> u32[1] {
  x
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SingleElementEnumArrayParam) {
  constexpr std::string_view program =
      R"(
enum Foo : u2 {}
fn f(x: Foo[1]) -> Foo[1] {
  x
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, BitSliceCast) {
  constexpr std::string_view program =
      R"(
fn main(x: u2) -> u1 {
  x as u1
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParametricDefaultInStruct) {
  constexpr std::string_view program = R"(
struct Foo <X: u32, Y: u32 = {X + u32:1}, Z: u32 = {Y + u32:1}> {
    a: uN[X],
    b: uN[Y],
    c: uN[Z]
}

fn make_zero_foo<X: u32>() -> Foo<X> {
  zero!<Foo<X>>()
}

fn test() -> Foo<u32:5> {
 make_zero_foo<u32:5>()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParametricStructReverseOrderParametrics) {
  constexpr std::string_view program = R"(
struct Foo<X: u32, Y: u32, Z:u32 = {X}> {
    a: uN[X],
    b: uN[Y],
    c: uN[Z],
}

fn make_zero_foo<X: u32, Y: u32>() -> Foo<Y, X> {
  Foo<Y, X> { a: zero!<uN[Y]>(), b: zero!<uN[X]>(), c: zero!<uN[Y]>() }
}

fn test() -> Foo<u32:6, u32:5> {
 make_zero_foo<u32:5, u32:6>()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, BitSliceSyntax) {
  constexpr std::string_view program =
      R"(
fn f(x: u4) -> u2 {
  x[:2]+x[-2:]+x[1:3]+x[-3:-1]+x[0:-2]
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ArrayConcat0) {
  constexpr std::string_view program =
      R"(
fn f(in1: u32[2]) -> u32 {
  let x : u32[4] = in1 ++ in1;
  x[u32:0]
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, PackageLevelConstantArray) {
  constexpr std::string_view program =
      R"(const FOO = u8[2]:[1, 2];
fn f() -> u8[2] { FOO }
fn g() -> u8[2] { FOO }
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, StructWithConstSizedArray) {
  constexpr std::string_view program =
      R"(
const THING_COUNT = u32:2;
type Foo = (
  u32[THING_COUNT]
);
fn get_thing(x: Foo, i: u32) -> u32 {
  let things: u32[THING_COUNT] = x.0;
  things[i]
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NestedTupleSignature) {
  constexpr std::string_view program =
      R"(
    type Foo = u3;

    type MyTup = (u6, u1);

    type TupOfThings = (u1, MyTup, Foo);

    type MoreStructured = (
      TupOfThings[3],
      u3,
      u1,
    );

    type Data = (u64, u1);

    fn main(r: u9, l: u10, input: MoreStructured) -> (u9, u10, Data) {
      (u9:0, u10:0, (u64:0, u1:0))
    }
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, PackageLevelConstantArrayAccess) {
  constexpr std::string_view program =
      R"(
const FOO = u8[2]:[1, 2];
fn f() -> u8 { FOO[u32:0] }
fn g() -> u8 { FOO[u32:1] }
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ModuleLevelConstantDims) {
  constexpr std::string_view program =
      R"(
const BATCH_SIZE = u32:17;

fn main(x: u32[BATCH_SIZE]) -> u32 {
  x[u32:16]
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, DerivedToBitsNestedStructs) {
  constexpr std::string_view kDslxProgram = R"(
#[derive(ToBits)]
pub struct A { x: u32 }

#[derive(ToBits)]
pub struct B { a: A }

#[derive(ToBits)]
pub struct C { b: B }

pub fn main(c: C) -> bits[32] {
  c.to_bits()
}
)";

  XLS_ASSERT_OK(ConvertModuleForTest(kDslxProgram));
}

TEST_F(IrConverterTest, BitSliceUpdate) {
  constexpr std::string_view program =
      R"(
fn main(x: u32, y: u16, z: u8) -> u32 {
  bit_slice_update(x, y, z)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertImplFunctionOnStructMember) {
  constexpr std::string_view program = R"(
  struct F {}

  impl F {
    pub fn bar(self) -> F { F {} }
  }

  struct G { f: F }
  impl G {
    pub fn foo(self) -> F {
      self.f.bar()
    }
  }

  fn top_fn() -> F {
    let g = G { f: F {} };
    g.foo()
  }

  fn another_fn() -> G {
    G { f: F {} }
  }
  )";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertInstanceMethodOnParametricStruct) {
  constexpr std::string_view program = R"(
  struct S<A: u32> {
    val: uN[A]
  }

  impl S<A> {
    fn foo(self, a: uN[A]) -> uN[A] { a + self.val }
  }

  fn main() -> (u16, u32) {
    const X = S<16>{val: 1}.foo(100);
    const Y = S<32>{val: 2}.foo(200);
    (X, Y)
  }
  )";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertParametricInstanceMethodOnParametricStruct) {
  constexpr std::string_view program = R"(
  struct S<A: u32> {
    val: uN[A]
  }

  impl S<A> {
    fn foo<N: u32>(self, a: uN[A]) -> uN[A] { a + self.val }
  }

  fn main() -> (u16, u16, u32) {
    const X = S<16>{val: 1}.foo<24>(100);
    const Y = S<16>{val: 2}.foo<16>(100);
    const Z = S<32>{val: 2}.foo<16>(200);
    (X, Y, Z)
  }
  )";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, EmptyArray) {
  constexpr std::string_view program = R"(
    fn main() -> u32[0] {
      u32[0]:[]
    }
)";

  auto import_data = CreateImportDataForTest();
  EXPECT_THAT(ConvertOneFunctionForTest(program, "main", import_data),
              StatusIs(absl::StatusCode::kInvalidArgument,
                       HasSubstr("Array u32[0]:[] was empty")));
}

TEST_F(IrConverterTest, ImplColonRef) {
  constexpr std::string_view program = R"(
  struct F {}

  impl F {
    fn bar() -> u32 { u32:0 }
  }

  fn bar() -> u32 { u32:0 }

  fn top_fn() -> u32 {
    F::bar()
  }
  )";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

constexpr std::string_view kParametricDefaultBuiltin = R"(
struct Foo <X: u32, Y: u32 = {clz(X)}> {
    a: uN[X],
    b: uN[Y],
}

fn make_zero_foo<X: u32>() -> Foo<X> {
  zero!<Foo<X>>()
}

fn test() -> Foo<u32:5> {
  make_zero_foo<u32:5>()
}
)";

TEST_F(IrConverterTest, ParametricDefaultBuiltinInStruct) {
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kParametricDefaultBuiltin));
  ExpectIr(converted);
}

constexpr std::string_view kParametricDefaultClog2 = R"(
import std;

struct Foo <X: u32, Y: u32 = {std::clog2(X)}> {
    a: uN[X],
    b: uN[Y],
}

fn make_zero_foo<X: u32>() -> Foo<X> {
  zero!<Foo<X>>()
}

fn test() -> Foo<u32:5> {
  make_zero_foo<u32:5>()
}
)";

TEST_F(IrConverterTest, ParametricDefaultClog2InStruct) {
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kParametricDefaultClog2));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SimpleImpl) {
  constexpr std::string_view program = R"(
  struct F {}

  impl F {
    pub fn bar() -> u32 { u32:0 }
  }

  fn top_fn() -> u32 {
    F::bar()
  }
  )";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SimpleImplMethod) {
  constexpr std::string_view program = R"(
  struct F {}

  impl F {
    pub fn bar(self) -> F { self }
  }

  fn top_fn() -> F {
    let f = F {};
    f.bar()
  }
  )";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
