// Copyright 2021 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests the IR output generated by DSLX imports and cross-module features.
// The IR is not checked for validity; it is only tested against a
// pre-constructed golden file.

#include <string>
#include <string_view>

#include "gtest/gtest.h"
#include "xls/common/status/matchers.h"
#include "xls/dslx/create_import_data.h"
#include "xls/dslx/import_data.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/parse_and_typecheck.h"
#include "xls/dslx/type_system/typecheck_test_utils.h"

namespace xls::dslx {
namespace {

TEST_F(IrConverterTest, ConstexprImport) {
  // Place the *imported* module into the import cache.
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
import std;

pub const MY_CONST = bits[32]:5;
pub const MY_OTHER_CONST = std::clog2(MY_CONST);

pub fn constexpr_fn(arg: u32) -> u32 {
  arg * MY_CONST
}
)";
  XLS_ASSERT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn f() -> u32 {
  let x = stuff::constexpr_fn(stuff::MY_OTHER_CONST);
  x
}
)";

  // Convert the *importer* module to IR.
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ZeroMacroImportedStructInProcInit) {
  ImportData import_data = CreateImportDataForTest();

  constexpr std::string_view imported = R"(
pub struct S { field: u32 }
  )";
  XLS_EXPECT_OK(
      ParseAndTypecheck(imported, "imported.x", "imported", &import_data));

  constexpr std::string_view program = R"(
import imported;

proc main {
  init {
    // IR converter cares whether `imported::S` has a `MetaType` here, only for
    // macro invocations inside a proc init.
    zero!<imported::S>()
  }
  config() {
    ()
  }
  next(s: imported::S) {
    s
  }
}
  )";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(program, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapImportedFunction) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub fn some_function(x: u32) -> u32 { x }
)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn main() -> u32[2] {
  map([u32:1, u32:2], stuff::some_function)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapImportedParametricFunction) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub fn some_function<N: u32>(x: uN[N]) -> uN[N] { uN[N]:0 }
)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn main() -> u4[2] {
  map([u4:1, u4:2], stuff::some_function<u32:4>)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ImportedParametricFnWithDefault) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub fn some_function<N: u32, M: u32 = {N + u32:1}>() -> uN[M] { uN[M]:0 }
)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn main() -> u5 {
  let var = stuff::some_function<u32:4>();
  var
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, TwoLevelsOfParametricCallsAcrossImportBoundary) {
  // In this example, TIv2 will create a `ParametricEnv` for the cross-module
  // baz->foo call, and that should be the caller env for the internal foo->bar
  // call. If that caller env gets incorrectly siloed in state for the
  // "imported" module that creates it, IR conversion will fail.

  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported = R"(
fn bar<N: u32>(a: uN[N]) -> uN[N] { a }

pub fn foo<A: u32>(a: uN[A]) -> uN[A] { bar(a) }

)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer = R"(
import fake.imported.stuff as imported;

fn baz<N: u32>(a: uN[N]) -> uN[N] { imported::foo(a) }

fn main() {
  baz(u32:5);
  baz(u24:6);
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ImportConstantArray) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
const SIZE = u32:5;
pub const ARRAY = u32[SIZE]:[1, 2, 3, 4, 5];
)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn main() -> u32[5] {
  let var = stuff::ARRAY;
  var
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ImportStruct) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub struct S { x: u5[2] }
)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn main() -> u5 {
  let s = stuff::S{x: [u5:1, u5:2]};
  s.x[u1:1]
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ImportStructImpl) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub struct S { x: u5 }

impl S {
  fn X(self) -> u5 { self.x }
}
)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn main() -> u5 {
  let s = stuff::S{x: u5:1};
  s.X()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ChainOfImports) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view first_imported_program = R"(
pub const SOME_CONSTANT = u32:1;
)";
  XLS_EXPECT_OK(ParseAndTypecheck(first_imported_program,
                                  "fake/imported/first.x",
                                  "fake.imported.first", &import_data));

  constexpr std::string_view second_imported_program = R"(
import fake.imported.first;

pub fn get_const() -> u32 {
  first::SOME_CONSTANT
}
)";
  XLS_EXPECT_OK(ParseAndTypecheck(second_imported_program,
                                  "fake/imported/second.x",
                                  "fake.imported.second", &import_data));

  constexpr std::string_view importer_program = R"(
import fake.imported.second;

fn main() -> u1 {
  uN[second::get_const()]:0
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParametricConstexprImport) {
  // Place the *imported* module into the import cache.
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub const MY_CONST = bits[32]:5;

pub fn constexpr_fn<N:u32>(arg: bits[N]) -> bits[N] {
  arg * MY_CONST
}

)";
  XLS_ASSERT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn f() -> u32 {
  let x = stuff::constexpr_fn(stuff::MY_CONST);
  x
}
)";

  // Convert the *importer* module to IR.
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ImportEnumValue) {
  auto import_data = CreateImportDataForTest();

  constexpr std::string_view import_module = R"(
import std;

pub const MY_CONST = u32:5;
pub enum ImportEnum : u16 {
  SINGLE_MY_CONST = MY_CONST as u16,
  DOUBLE_MY_CONST = std::clog2(MY_CONST) as u16 * u16:2,
  TRIPLE_MY_CONST = (MY_CONST * u32:3) as u16,
}
)";
  XLS_ASSERT_OK(ParseAndTypecheck(import_module, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));

  constexpr std::string_view importer_module = R"(
import fake.imported.stuff;

type ImportedEnum = stuff::ImportEnum;

fn main(x: u32) -> u32 {
  stuff::ImportEnum::TRIPLE_MY_CONST as u32 +
      (ImportedEnum::DOUBLE_MY_CONST as u32) +
      (stuff::ImportEnum::SINGLE_MY_CONST as u32)
})";

  // Convert the importer module to IR.
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_module, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertOneFunctionWithImport) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view import_module = R"(
pub fn a() -> u32 {
  u32:42
}
)";
  XLS_ASSERT_OK(
      ParseAndTypecheck(import_module, "a.x", "a", &import_data).status());

  constexpr std::string_view importer_module = R"(
import a;

fn main(x: u32) -> u32 {
  a::a()
})";

  // Convert the importer module to IR.
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(importer_module, "main", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeImportedParametricFnInProc) {
  ImportData import_data = CreateImportDataForTest();
  constexpr std::string_view imported = R"(
pub fn square<N: u32>(x:uN[N]) -> uN[N] { x * x }
)";
  XLS_EXPECT_OK(
      ParseAndTypecheck(imported, "imported.x", "imported", &import_data));

  constexpr std::string_view program = R"(
import imported;

proc Counter {
  in_ch: chan<u10> in;
  out_ch: chan<u10> out;

  init { imported::square<u32:10>(u10:2) }

  config(in_ch: chan<u10> in, out_ch: chan<u10> out) {
    (in_ch, out_ch)
  }

  next(state: u10) {
    let (tok, in_data) = recv(join(), in_ch);
    let x = imported::square<u32:10>(in_data);
    let next_state = state + x;
    let tok = send(tok, out_ch, next_state);

    next_state
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(program, "Counter", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SpawnImportedProc) {
  ImportData import_data = CreateImportDataForTest();

  constexpr std::string_view kImported = R"(
pub proc importee {
  init { }
  config() { () }
  next(_: ()) { () }
}
)";
  XLS_EXPECT_OK(
      ParseAndTypecheck(kImported, "imported.x", "imported", &import_data));

  constexpr std::string_view kProgram = R"(
import imported;

pub proc main {
  init { }
  config() {
    spawn imported::importee();
    ()
  }
  next(_: ()) { () }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(kProgram, "main", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CallImportedFnFromNext) {
  ImportData import_data = CreateImportDataForTest();

  constexpr std::string_view kImported = R"( pub fn callee() -> u32 { u32:0 })";
  XLS_EXPECT_OK(
      ParseAndTypecheck(kImported, "imported.x", "imported", &import_data));

  constexpr std::string_view kProgram = R"(
import imported;

proc Main {
    init { u32:1 }
    config() { () }
    next(state: u32) {
      state + imported::callee()
    }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(kProgram, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SpawnedCallImportedFnFromNext) {
  ImportData import_data = CreateImportDataForTest();

  constexpr std::string_view kImported =
      R"( pub fn callee() -> u32 { u32:0 } )";
  XLS_EXPECT_OK(
      ParseAndTypecheck(kImported, "imported.x", "imported", &import_data));

  constexpr std::string_view kProgram = R"(
import imported;

proc Spawned {
    init { u32:1 }
    config() { () }
    next(state: u32) {
      state + imported::callee()
    }
}

pub proc Main {
    init {}
    config() {
      spawn Spawned();
      ()
    }
    next(_: ()) { () }
}

)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(kProgram, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SpawnedCallImportedFnFromNextBoundaryChannels) {
  ImportData import_data = CreateImportDataForTest();

  constexpr std::string_view kImported =
      R"( pub fn callee() -> u32 { u32:0 } )";
  XLS_EXPECT_OK(
      ParseAndTypecheck(kImported, "imported.x", "imported", &import_data));

  constexpr std::string_view kProgram = R"(
import imported;

proc Spawned {
    init { u32:1 }
    config() { () }
    next(state: u32) {
      state + imported::callee()
    }
}

pub proc Main {
    init {}
    config(ic: chan<u32>in) {
      spawn Spawned();
      ()
    }
    next(_: ()) { () }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(kProgram, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParametricSpawnedCallImportedFnFromNext) {
  ImportData import_data = CreateImportDataForTest();

  constexpr std::string_view kImported =
      R"( pub fn callee<N: u32>() -> uN[N] { uN[N]:0 } )";
  XLS_EXPECT_OK(
      ParseAndTypecheck(kImported, "imported.x", "imported", &import_data));

  constexpr std::string_view kProgram = R"(
import imported;

proc Spawned<N: u32> {
    init { uN[N]:1 }
    config() { () }
    next(state: uN[N]) {
      state + imported::callee<N>()
    }
}

pub proc Main {
    init {}
    config() {
      spawn Spawned<u32:10>();
      ()
    }
    next(_: ()) { () }
}

)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(kProgram, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

constexpr std::string_view kImported = R"(
pub proc Importee<N: u32> {
  c: chan<uN[N]> out;
  init { uN[N]:123 }
  config(output_c: chan<uN[N]> out) {
    (output_c,)
  }
  next(state: uN[N]) {
    send(token(), c, state);
    state
  }
}
  )";
constexpr std::string_view kProgram = R"(
import imported;

pub proc Importer {
    init {}
    config() {
      let (s, _) = chan<u16>("chan0");
      spawn imported::Importee<u32:16>(s);
      ()
    }
    next(_: ()) { () }
  }
)";

TEST_F(IrConverterTest, SpawnImportedParametricProc) {
  ImportData import_data = CreateImportDataForTest();
  XLS_EXPECT_OK(
      ParseAndTypecheck(kImported, "imported.x", "imported", &import_data));
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(kProgram, "Importer", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ProcScopedImport) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
import std;

pub const MY_CONST = bits[32]:5;
pub const MY_OTHER_CONST = std::clog2(MY_CONST);

pub fn constexpr_fn(arg: u32) -> u32 {
  arg * MY_CONST
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(
      TypecheckedModule tm,
      ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                        "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn f() -> u32 {
  let x = stuff::constexpr_fn(stuff::MY_OTHER_CONST);
  x
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ProcScopedProcAliasToImportedProc) {
  ImportData import_data = CreateImportDataForTest();

  constexpr std::string_view imported = R"(
pub proc Foo<N: u32> {
  c: chan<uN[N]> out;
  init { uN[N]:1 }
  config(output_c: chan<uN[N]> out) {
    (output_c,)
  }
  next(i: uN[N]) {
    let tok = send(join(), c, i);
    i + uN[N]:2
  }
}
  )";
  XLS_EXPECT_OK(
      ParseAndTypecheck(imported, "imported.x", "imported", &import_data));

  constexpr std::string_view program = R"(
import imported;
pub proc FooAlias = imported::Foo<16>;
  )";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(program, "FooAlias", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeImportedParametricFn) {
  ImportData import_data = CreateImportDataForTest();
  constexpr std::string_view imported = R"(
pub fn importee<N: u32>(i: uN[N]) -> uN[N] { i }
)";
  XLS_EXPECT_OK(
      ParseAndTypecheck(imported, "imported.x", "imported", &import_data));
  constexpr std::string_view program = R"(
import imported;

pub fn importer() -> u24 {
  let _ = imported::importee<u32:8>(u8:1);
  let _ = imported::importee<u32:16>(u16:2);
  imported::importee<u32:24>(u24:3)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(program, "importer", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, DISABLED_UseOfClog2InModuleScopedConstantDefinition) {
  constexpr std::string_view program = R"(#![feature(use_syntax)]
use std::clog2;

const MAX_BITS: u32 = clog2(u32:256);

fn main() -> u32 {
    MAX_BITS
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, DISABLED_UseTreeEntryCallInParametric) {
  constexpr std::string_view program = R"(
  #![feature(use_syntax)]
  use std::is_pow2;
  fn f<N: u32>(x: bits[N]) -> bool { is_pow2(x) }
  fn main() -> bool { f(u2:3) }
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ProcScopedTwoParametricCallsAcrossImportBoundary) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported = R"(
fn bar<N: u32>(a: uN[N]) -> uN[N] { a }

pub fn foo<A: u32>(a: uN[A]) -> uN[A] { bar(a) }

)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer = R"(
import fake.imported.stuff as imported;

fn baz<N: u32>(a: uN[N]) -> uN[N] { imported::foo(a) }

fn main() {
  baz(u32:5);
  baz(u24:6);
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SpawnTwoImportedParametricProc) {
  ImportData import_data = CreateImportDataForTest();
  constexpr std::string_view imported = R"(
proc Leaf<P: u32> {
  c: chan<uN[P]> out;
  init { uN[P]:123 }
  config(output_c: chan<uN[P]> out) {
    (output_c,)
  }
  next(state: uN[P]) {
    send(token(), c, state);
    state
  }
}

pub proc Importee<M: u32> {
  init { uN[M]:456 }
  config(output_c: chan<uN[M]> out) {
    spawn Leaf<M>(output_c);
    ()
  }
  next(state: uN[M]) {
    state
  }
}
  )";
  XLS_EXPECT_OK(
      ParseAndTypecheck(imported, "imported.x", "imported", &import_data));

  constexpr std::string_view program = R"(
import imported;

proc Local<N: u32> {
  init { uN[N]:789 }
  config(output_c: chan<uN[N]> out) {
    spawn imported::Importee<N>(output_c);
    ()
  }
  next(state: uN[N]) {
    state
  }
}

pub proc Main {
    init {}
    config() {
      let (s, _) = chan<u16>("chan0");
      spawn Local<u32:16>(s);
      ()
    }
    next(_: ()) { () }
  }
)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(program, "Main", import_data));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
