// Copyright 2021 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests the IR output generated by DSLX `let` bindings and destructuring
// operations. The IR is not checked for validity; it is only tested against a
// pre-constructed golden file.

#include <string>
#include <string_view>

#include "gtest/gtest.h"
#include "xls/common/status/matchers.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/run_routines/run_comparator.h"
#include "xls/dslx/run_routines/run_routines.h"
#include "xls/dslx/type_system/typecheck_test_utils.h"

namespace xls::dslx {
namespace {

TEST_F(IrConverterTest, NamedConstant) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let foo: u32 = u32:42;
  foo
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, Concat) {
  constexpr std::string_view program =
      R"(fn f(x: bits[31]) -> u32 {
  bits[1]:1 ++ x
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParameterNamePreservedOnLetAlias) {
  constexpr std::string_view program = R"(
pub fn my_fun(baz: u32) -> u32 {
  let foo = baz;
  foo
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "my_fun"));

  // Expect the parameter to retain its original DSLX name `baz` in IR.
  EXPECT_EQ(converted, R"(package test_module

file_number 0 "test_module.x"

top fn __test_module__my_fun(baz: bits[32] id=1) -> bits[32] {
  ret baz: bits[32] = param(name=baz, id=1)
}
)");
}

TEST_F(IrConverterTest, TwoPlusTwo) {
  constexpr std::string_view program =
      R"(fn two_plus_two() -> u32 {
  u32:2 + u32:2
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "two_plus_two"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SignedDiv) {
  constexpr std::string_view program =
      R"(fn signed_div(x: s32, y: s32) -> s32 {
  x / y
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "signed_div"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NegativeX) {
  constexpr std::string_view program =
      R"(fn negate(x: u32) -> u32 {
  -x
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "negate"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetBinding) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let x: u32 = u32:2;
  x+x
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetTupleBinding) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:2, u32:3);
  let (x, y) = t;
  x+y
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetTupleBindingNested) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:2, (u32:3, (u32:4,), u32:5));
  let (x, (y, (z,), a)) = t;
  x+y+z+a
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetTupleBindingRestOfTupleNestedNone) {
  constexpr std::string_view program =
      R"(
#[test]
fn f() {
  let t = (u32:1, (u32:2, (u32:3,), u32:4));
  let (x, .., (y, .., (z, ..), a)) = t;
  assert_eq(x+y+z+a, u32:10)
})";
  RunComparator run_comparator(CompareMode::kInterpreter);
  XLS_ASSERT_OK(ParseAndTest(program, "", "test_module.x",
                             ParseAndTestOptions{
                                 .run_comparator = &run_comparator,
                             }));
}

TEST_F(IrConverterTest, LetTupleBindingRestOfTupleNested) {
  constexpr std::string_view program =
      R"(
#[test]
fn f() {
  let t = (u32:1, u32:2, u32:3, (u32:4, u32:5, (u32:6, u32:7), u32:5));
  let (x, .., (.., y, (z, ..), a)) = t;
  assert_eq(x+y+z+a, u32:17)
})";
  RunComparator run_comparator(CompareMode::kInterpreter);
  XLS_ASSERT_OK(ParseAndTest(program, "", "test_module.x",
                             ParseAndTestOptions{
                                 .run_comparator = &run_comparator,
                             }));
}

TEST_F(IrConverterTest, LetTupleBindingWildcardNested) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:2, u32:3, (u32:4, u32:5, (u32:6,u32:7), u32:8));
  let (x, _, (y, _, (z, _), a)) = t;
  x+y+z+a
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetTupleBindingWildcard) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:2, u32:3);
  let (x, _) = t;
  x
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetTupleBindingRestOfTuple) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:2, u32:3, u32:4);
  let (x, ..) = t;
  x
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetTupleBindingRestOfTupleNone) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:2,);
  let (x, ..) = t;
  x
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetTupleBindingRestOfTupleBeginning) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:2, u32:3, u32:4);
  let (.., x) = t;
  x
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, LetTupleBindingRestOfTupleSkipsMiddle) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:1, u32:2, u32:3, u32:4);
  let (x, .., y) = t;
  x+y
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
