// Copyright 2021 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests the IR output generated by DSLX `for` and `unroll_for` loops.
// The IR is not checked for validity; it is only tested against a
// pre-constructed golden file.

#include <string>
#include <string_view>

#include "gtest/gtest.h"
#include "xls/common/status/matchers.h"
#include "xls/dslx/create_import_data.h"
#include "xls/dslx/import_data.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/type_system/typecheck_test_utils.h"

namespace xls::dslx {
namespace {

TEST_F(IrConverterTest, CountedFor) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  for (i, accum): (u32, u32) in u32:0..u32:4 {
    accum + i
  }(u32:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConstFor) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  const for (i, accum): (u32, u32) in u32:0..u32:4 {
    accum + i
  }(u32:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ForOverArrayOfItems) {
  constexpr std::string_view program = R"(
fn main(a: (u7, u7)[3]) -> u7 {
  for (t, accum): ((u7, u7), u7) in a {
    accum + t.0 + t.1
  }(u7:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "main"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ForOverArrayLiteral) {
  constexpr std::string_view program = R"(
fn main() -> u7 {
  for (t, accum): ((u7, u7), u7) in (u7, u7)[2]:[(u7:0, u7:1), (u7:2, u7:3)] {
    accum + t.0 + t.1
  }(u7:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "main"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CountedForDestructuring) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = for (i, (x, y)): (u32, (u32, u8)) in u32:0..u32:4 {
    (x + i, y)
  }((u32:0, u8:0));
  t.0
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CountedForParametricConst) {
  constexpr std::string_view program =
      R"(fn f<N: u32>(x: bits[N]) -> u32 {
  for (i, accum): (u32, u32) in u32:0..N {
    accum + i
  }(u32:0)
}
fn main() -> u32 {
  f(bits[2]:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CountedForInvokingFunctionFromBody) {
  constexpr std::string_view program =
      R"(fn my_id(x: u32) -> u32 { x }
fn f() -> u32 {
  for (i, accum): (u32, u32) in u32:0..u32:4 {
    my_id(accum + i)
  }(u32:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CountedForVariableRange) {
  constexpr std::string_view program =
      R"(fn f(x:u32) -> u32 {
  for (i, accum): (u32, u32) in u32:0..x {
    accum + i
  }(u32:0)
}
)";
  auto status_or_ir = ConvertOneFunctionForTest(program, "f");
  ASSERT_FALSE(status_or_ir.ok());
}

TEST_F(IrConverterTest, CountedForWithLoopInvariants) {
  constexpr std::string_view program =
      R"(
fn f(outer_thing_1: u32, outer_thing_2: u32) -> u32 {
  let outer_thing_3: u32 = u32:42;
  let outer_thing_4: u32 = u32:24;
  for (i, accum): (u32, u32) in u32:0..u32:4 {
    accum + i + outer_thing_1 + outer_thing_2 + outer_thing_3 + outer_thing_4
  }(u32:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForSimple) {
  constexpr std::string_view program = R"(
fn test() -> u32 {
  unroll_for!(i, acc): (u32, u32) in u32:0..u32:4 {
    i + acc
  }(u32:0)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForNonU32) {
  constexpr std::string_view program = R"(
fn test() -> u8 {
  unroll_for!(i, acc): (u8, u8) in u8:0..u8:4 {
    i + acc
  }(u8:0)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithSignedIterable) {
  constexpr std::string_view program = R"(
fn test() -> s32 {
  unroll_for!(i, acc): (s32, s32) in [-s32:2, s32:0, s32:5] {
    i + acc
  }(s32:0)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithoutIndexName) {
  constexpr std::string_view program = R"(
fn test() -> u32 {
  unroll_for!(_, acc): (u32, u32) in u32:0..u32:4 {
    acc + u32:2
  }(u32:0)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithoutAccName) {
  constexpr std::string_view program = R"(
fn test() -> u32 {
  unroll_for!(i, _): (u32, u32) in u32:0..u32:4 {
    trace_fmt!("{}", i);
    i
  }(u32:0)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithoutIndexAccTypeAnnotation) {
  constexpr std::string_view program = R"(
proc SomeProc {
  init { () }
  config() { }
  next(state: ()) {
    unroll_for! (i, a) in u32:0..u32:4 {
      a + i
    }(u32:0);
  }
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForNested) {
  constexpr std::string_view program = R"(
fn test() -> u32 {
  unroll_for!(i, acc): (u32, u32) in u32:0..u32:4 {
    let x = unroll_for!(j, acc2): (u32, u32) in u32:3..u32:6 {
      j + acc2
    }(u32:11);
    x + i + acc
  }((u32:0))
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithArrayAsIterable) {
  constexpr std::string_view program = R"(
fn test() -> u32 {
  unroll_for!(i, acc): (u32, u32) in [u32:3, u32:4, u32:1] {
    i + acc
  }(u32:0)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithNonConstexprIterable) {
  constexpr std::string_view program = R"(
fn test(x:u32, y:u32) -> u32 {
  unroll_for!(i, acc): (u32, u32) in [x, y] {
    i + acc
  }(u32:0)
}
)";

  auto import_data = CreateImportDataForTest();
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithNonBitsIterable) {
  constexpr std::string_view program = R"(
fn test() -> u32 {
  unroll_for!(i, acc): ((u32, u32), u32) in [(u32:0, u32:5)] {
    i.0 + acc
  }(u32:0)
}
)";

  auto import_data = CreateImportDataForTest();
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithParametric) {
  constexpr std::string_view program = R"(
fn test<SIZE:u32>() -> bits[SIZE] {
  unroll_for!(i, acc): (bits[SIZE], bits[SIZE]) in bits[SIZE]:0..bits[SIZE]:4 {
    i + acc
  }(zero!<bits[SIZE]>())
}

fn foo() -> u8 {
  (test<u32:7>() as u8) + test<u32:8>()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollForWithTupleAccumulator) {
  constexpr std::string_view program = R"(
fn test() -> (u32, u32) {
  unroll_for!(i, (acc1, acc2)): (u32, (u32, u32)) in u32:0..u32:4 {
    (i + acc1, i + acc2)
  }((u32:2, u32:3))
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ImportedUnrollForCallsParametric) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub fn foo_param<N: u32>() -> u32 {
  N
}

pub fn loop() -> u32 {
  unroll_for!(i, _): (u32, u32) in u32:0..5 {
      foo_param<i>();
  }((u32:0))
}

)";
  XLS_ASSERT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view program = R"(
import fake.imported.stuff;

fn main() -> u32 {
  stuff::loop()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(
                               program, "main", import_data, kNoVerifyOptions));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CountedForWithTupleAccumulator) {
  constexpr std::string_view program =
      R"(
fn f() -> (u32, u32) {
  for (i, (a, b)): (u32, (u32, u32)) in u32:0..u32:4 {
    (a+b, b+u32:1)
  }((u32:0, u32:1))
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ArrayUpdateInLoop) {
  constexpr std::string_view program =
      R"(
fn main() -> u8[2] {
  for (i, accum): (u32, u8[2]) in u32:0..u32:2 {
    update(accum, i, i as u8)
  }(u8[2]:[0, 0])
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FailInsideFor) {
  constexpr std::string_view program = R"(
fn main(x: u32) -> u32 {
  for (i, x): (u32, u32) in u32:0..u32:1 {
    fail!("failure", x)
  }(u32:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FailOutsideFor) {
  constexpr std::string_view program = R"(
fn main(x: u32) -> u32 {
  let x = for (i, x): (u32, u32) in u32:0..u32:1 {
    x
  }(u32:0);
  fail!("failure", x)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FailInsideForWithTupleAccum) {
  constexpr std::string_view program = R"(
fn main(x: u32) -> (u32, u32) {
  for (i, (x, y)): (u32, (u32, u32)) in u32:0..u32:1 {
    fail!("failure", (x, y))
  }((u32:0, u32:0))
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CountedForParametricRefInBody) {
  constexpr std::string_view program =
      R"(
fn f<N:u32>(init: bits[N]) -> bits[N] {
  for (i, accum): (u32, bits[N]) in u32:0..u32:4 {
    accum as bits[N]
  }(init)
}

fn main() -> u32 {
  f(u32:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnrollFor) {
  // Based on UnrollForWithoutIndexAccTypeAnnotation
  constexpr std::string_view program = R"(
proc SomeProc {
  init { () }
  config() { }
  next(state: ()) {
    unroll_for! (i, a) in u32:0..u32:4 {
      a + i
    }(u32:0);
  }
})";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "SomeProc"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SpawnInTopLevelUnrollFor) {
  constexpr std::string_view program = R"(
proc SubProc {
  out_ch: chan<u32> out;
  in_ch: chan<u32> in;
  init { }
  config(my_out: chan<u32> out, my_in: chan<u32> in) {
    (my_out, my_in)
  }
  next(state: ()) {()}
}

proc Top {
  init {}
  config() {
    let (outs, ins) = chan<u32>[4]("chans");
    unroll_for!(i, _) : (u32, ()) in u32:0..u32:4 {
      spawn SubProc(outs[i], ins[i]);
    }(());
    ()
  }
  next(state: ()) { state }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "Top"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SpawnInParametricProcUnrollFor) {
  constexpr std::string_view program = R"(
proc SubProc<N: u32> {
  out_ch: chan<uN[N]> out;
  in_ch: chan<uN[N]> in;
  init { }
  config(my_out: chan<uN[N]> out, my_in: chan<uN[N]> in) {
    (my_out, my_in)
  }
  next(state: ()) { () }
}

proc Top {
  init {}
  config() {
    let (outs, ins) = chan<u32>[4]("chans");
    unroll_for!(i, _) : (u32, ()) in u32:0..u32:4 {
      spawn SubProc<u32:32>(outs[i], ins[i]);
    }(());
    ()
  }
  next(state: ()) { state }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "Top"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SendRecvInUnrollFor) {
  constexpr std::string_view program = R"(
proc Top {
  outs: chan<u32>[4] out;
  ins: chan<u32>[4] in;
  init {}
  config(outs: chan<u32>[4] out, ins: chan<u32>[4] in) {
    (outs, ins)
  }
  next(state: ()) {
    unroll_for!(i, tok) : (u32, token) in u32:0..u32:4 {
      let tok = send(token(), outs[i], i);
      let (tok, _) = recv(tok, ins[i]);
      tok
    }(token());
  }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "Top"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParentChildSpawnInUnrolledParametricProc) {
  constexpr std::string_view program = R"(
proc Leaf<X: u32> {
  out_ch: chan<uN[X]> out;
  in_ch: chan<uN[X]> in;
  init { }
  config(my_out: chan<uN[X]> out, my_in: chan<uN[X]> in) {
    (my_out, my_in)
  }
  next(state: ()) { () }
}

proc Branch<I: u32> {
  out_ch: chan<uN[I]> out;
  in_ch: chan<uN[I]> in;
  init { }
  config(my_out: chan<uN[I]> out, my_in: chan<uN[I]> in) {
    let (outs, ins) = chan<uN[I]>[2]("chans");
    unroll_for!(i, _) : (u32, ()) in u32:0..u32:2 {
      spawn Leaf<I>(outs[i], ins[i]);
    }(());
    (my_out, my_in)
  }
  next(state: ()) { () }
}

proc Top {
  init {}
  config() {
    let (outs, ins) = chan<u32>[3]("chans");
    unroll_for!(i, _) : (u32, ()) in u32:0..u32:3 {
      spawn Branch<u32:32>(outs[i], ins[i]);
    }(());
    ()
  }
  next(state: ()) { state }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "Top"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParentChildSpawnInImportedUnrolledParametricProc) {
  ImportData import_data = CreateImportDataForTest();
  constexpr std::string_view imported = R"(
pub proc Leaf<X: u32> {
  out_ch: chan<uN[X]> out;
  in_ch: chan<uN[X]> in;
  init { }
  config(my_out: chan<uN[X]> out, my_in: chan<uN[X]> in) {
    (my_out, my_in)
  }
  next(state: ()) { () }
}
)";
  XLS_EXPECT_OK(
      ParseAndTypecheck(imported, "imported.x", "imported", &import_data));

  constexpr std::string_view program = R"(
import imported;
proc Branch<N: u32> {
  out_ch: chan<uN[N]> out;
  in_ch: chan<uN[N]> in;
  init { }
  config(my_out: chan<uN[N]> out, my_in: chan<uN[N]> in) {
    let (outs, ins) = chan<uN[N]>[2]("chans");
    unroll_for!(i, _) : (u32, ()) in u32:0..u32:2 {
      spawn imported::Leaf<N>(outs[i], ins[i]);
    }(());
    (my_out, my_in)
  }
  next(state: ()) { () }
}

proc Top {
  init {}
  config() {
    let (outs, ins) = chan<u32>[3]("chans");
    unroll_for!(i, _) : (u32, ()) in u32:0..u32:3 {
      spawn Branch<u32:32>(outs[i], ins[i]);
    }(());
    ()
  }
  next(state: ()) { state }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(program, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParentChildSpawnInImportedUnrolledProc) {
  ImportData import_data = CreateImportDataForTest();
  constexpr std::string_view imported = R"(
pub proc Leaf {
  out_ch: chan<u32> out;
  in_ch: chan<u32> in;
  init { }
  config(my_out: chan<u32> out, my_in: chan<u32> in) {
    (my_out, my_in)
  }
  next(state: ()) { () }
}
)";
  XLS_EXPECT_OK(
      ParseAndTypecheck(imported, "imported.x", "imported", &import_data));

  constexpr std::string_view program = R"(
import imported;
proc Branch{
  out_ch: chan<u32> out;
  in_ch: chan<u32> in;
  init { }
  config(my_out: chan<u32> out, my_in: chan<u32> in) {
    let (outs, ins) = chan<u32>[2]("chans");
    unroll_for!(i, _) : (u32, ()) in u32:0..u32:2 {
      spawn imported::Leaf(outs[i], ins[i]);
    }(());
    (my_out, my_in)
  }
  next(state: ()) { () }
}

proc Top {
  init {}
  config() {
    let (outs, ins) = chan<u32>[3]("chans");
    unroll_for!(i, _) : (u32, ()) in u32:0..u32:3 {
      spawn Branch(outs[i], ins[i]);
    }(());
    ()
  }
  next(state: ()) { state }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(program, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, DISABLED_LoopThroughTupleArray) {
  constexpr std::string_view program = R"(
pub fn make_bool_array() -> bool[2] {
    let enumerated = [(u32:0, u32:0), (u32:1, u32:1)];
    for ((_, i), x): ((u32, u32), bool[2]) in enumerated {
        update(x, i, true)
    }(zero!<bool[2]>())
}

fn main() -> bool[2] {
  make_bool_array()
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "main"));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
