// Copyright 2021 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests the IR output generated by DSLX `match` expressions.
// The IR is not checked for validity; it is only tested against a
// pre-constructed golden file.

#include <string>
#include <string_view>

#include "gtest/gtest.h"
#include "xls/common/status/matchers.h"
#include "xls/dslx/ir_convert/convert_options.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/run_routines/run_comparator.h"
#include "xls/dslx/run_routines/run_routines.h"
#include "xls/dslx/type_system/typecheck_test_utils.h"

namespace xls::dslx {
namespace {

TEST_F(IrConverterTest, MatchRestOfTupleBeginning) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:1, u32:2, u32:3, u32:4);
  match t {
    (.., u32:3, y) => y,
    _ => u32:0
  }
})";
  RunComparator run_comparator(CompareMode::kInterpreter);
  XLS_ASSERT_OK(ParseAndTest(program, "", "test_module.x",
                             ParseAndTestOptions{
                                 .run_comparator = &run_comparator,
                             }));
}

TEST_F(IrConverterTest, MatchRestOfTupleMiddle) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:1, u32:2, u32:3, u32:4);
  match t {
    (u32:1, .., y) => y,
    _ => u32:0
  }
})";
  RunComparator run_comparator(CompareMode::kInterpreter);
  XLS_ASSERT_OK(ParseAndTest(program, "", "test_module.x",
                             ParseAndTestOptions{
                                 .run_comparator = &run_comparator,
                             }));
}

TEST_F(IrConverterTest, MatchRestOfTupleEnd) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:1, u32:2, u32:3, u32:4);
  match t {
    (u32:1, y, ..) => y,
    _ => u32:0
  }
})";
  RunComparator run_comparator(CompareMode::kInterpreter);
  XLS_ASSERT_OK(ParseAndTest(program, "", "test_module.x",
                             ParseAndTestOptions{
                                 .run_comparator = &run_comparator,
                             }));
}

TEST_F(IrConverterTest, MatchTupleOfTuplesRestOfTuple) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:1, (u32:2, u32:3, u32:4), u32:5, u32:6);
  match t {
    (u32:1, .., a) => a,
    (u32:1, (b, ..), ..) => b,
    (u32:0, (.., d), ..) => d,
    (u32:0, (e, .., g), ..) => g,
    (.., h, u32:5) => h,
    _ => u32:0
  }
})";
  RunComparator run_comparator(CompareMode::kInterpreter);
  XLS_ASSERT_OK(ParseAndTest(program, "", "test_module.x",
                             ParseAndTestOptions{
                                 .run_comparator = &run_comparator,
                             }));
}

TEST_F(IrConverterTest, MatchRestOfTupleAsTrailingArm) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let t = (u32:1, u32:2);
  match t {
    (u32:1, .., a) => a,
    (..) => u32:1
  }
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "f"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, Match) {
  constexpr std::string_view program =
      R"(
fn f(x: u8) -> u2 {
  match x {
    u8:42 => u2:0,
    u8:64 => u2:1,
    _ => u2:2
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConstMatch) {
  constexpr std::string_view program =
      R"(
fn f() -> u2 {
  const COND = u8:5;
  const match COND {
    u8:0 => u2:0,
    _ => u2:1
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchDefaultOnly) {
  constexpr std::string_view program =
      R"(
fn f(x: u8) -> u2 {
  match x {
    _ => u2:2
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchDense) {
  constexpr std::string_view program =
      R"(
fn f(x: u2) -> u8 {
  match x {
    u2:0 => u8:42,
    u2:1 => u8:64,
    u2:2 => u8:128,
    _ => u8:255
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchIdentity) {
  constexpr std::string_view program =
      R"(
fn f(x: u8) -> u2 {
  match x {
    u8:42 => u2:3,
    _ => x as u2
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchPackageLevelConstant) {
  constexpr std::string_view program =
      R"(const FOO = u8:0xff;
fn f(x: u8) -> u2 {
  match x {
    FOO => u2:0,
    _ => x as u2
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchUnderLet) {
  constexpr std::string_view program =
      R"(
fn main(x: u8) -> u8 {
  let t = match x {
    u8:42 => u8:0xff,
    _ => x
  };
  t
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchDenseConsts) {
  constexpr std::string_view program =
      R"(
type MyU2 = u2;
const ZERO = MyU2:0;
const ONE = MyU2:1;
const TWO = MyU2:2;
fn f(x: u2) -> u8 {
  match x {
    ZERO => u8:42,
    ONE => u8:64,
    TWO => u8:128,
    _ => u8:255
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchWithlet) {
  constexpr std::string_view program =
      R"(
fn f(x: u8) -> u2 {
  match x {
    u8:42 => { let x = u2:0; x },
    u8:64 => { let x = u2:1; x },
    _ => { let x = u2:2; x }
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FailInMatch) {
  constexpr std::string_view program = R"(
fn main(x: u32) -> u32 {
  match x {
    u32:42 => fail!("failure", x),
    _ => x
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FailInMatchInvocation) {
  constexpr std::string_view program = R"(
fn do_fail(x: u32) -> u32 {
  fail!("failure", x)
}

fn main(x: u32) -> u32 {
  match x {
    u32:42 => do_fail(x),
    _ => x
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchMultiFail) {
  constexpr std::string_view program = R"(
fn main(x: u32) -> u32 {
  match x {
    u32:42 => fail!("failure_0", x),
    _ => fail!("failure_1", x+u32:1)
  }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchExhaustiveMultiplePatternLastArm) {
  constexpr std::string_view program = R"(
fn main(x: u2) -> u32 {
  match x {
    u2:0 | u2:1 => u32:0,
    u2:2 | u2:3 => u32:1,
  }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchExhaustiveOneRangeAndValueInSingleArm) {
  constexpr std::string_view program = R"(
  fn main(x: u2) -> u32 {
    match x {
      u2:0..u2:3 | u2:3 => u32:42,
    }
  }
  )";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchExhaustiveRangeInTrailingArm) {
  constexpr std::string_view program = R"(
  fn main(x: u2) -> u32 {
    match x {
      u2:3 => u32:42,
      u2:0..u2:3 => u32:64,
    }
  }
  )";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MatchRangeInclusiveEnd) {
  constexpr std::string_view program = R"(
fn main(x: u2) -> u32 {
match x {
 u2:0..=u2:3 => u32:1,
}
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
