// Copyright 2021 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests the IR output generated by DSLX `if` and `const if` conditional
// expressions. The IR is not checked for validity; it is only tested against a
// pre-constructed golden file.

#include <string>
#include <string_view>

#include "gtest/gtest.h"
#include "xls/common/status/matchers.h"
#include "xls/dslx/ir_convert/convert_options.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/type_system/typecheck_test_utils.h"

namespace xls::dslx {
namespace {

TEST_F(IrConverterTest, Conditional) {
  constexpr std::string_view program =
      R"(fn main(x: bool) -> u8 {
  if x { u8:42 } else { u8:24 }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConditionalsPlusStuff) {
  constexpr std::string_view program =
      R"(
fn foo(a: bool) -> u8 {
  let x = if a { u8:42 } else { u8:24 } + u8:1;
  let y = u8:1 + if a { u8:42 } else { u8:24 };
  let z = if a { u8:42 } else { u8:24 } + if a { u8:42 } else { u8:24 };
  x + y + z
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConstConditional) {
  constexpr std::string_view program =
      R"(
fn main() -> u32 {
  const if true {
    u16:42
  } else {
    u8:24
  } as u32
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConstIfOfParametricInFn) {
  constexpr std::string_view kProgram = R"(
fn const_if_disparate_types<A: u32>() -> u32 {
    let data = const if A == u32:0 {
        u16:600
    } else if A == u32:1 {
        u32:70000
    } else {
        u8:4
    };

    data as u32
}

fn main() -> u32 { const_if_disparate_types<u32:0>() }
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kProgram));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConstantsWithConditionalsPlusStuff) {
  constexpr std::string_view program =
      R"(
const A = true;
const X = if A { u8:42 } else { u8:24 } + u8:1;
const Y = u8:1 + if A { u8:42 } else { u8:24 };
const Z = if A { u8:42 } else { u8:24 } + if A { u8:42 } else { u8:24 };
fn main(x: bool) -> u8 { X + Y + Z }
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FailInTernaryConsequent) {
  constexpr std::string_view program = R"(
fn main(x: u32) -> u32 {
  if x == u32:0 { fail!("failure", x) } else { x }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FailInTernaryAlternate) {
  constexpr std::string_view program = R"(
fn main(x: u32) -> u32 {
  if x == u32:0 { x } else { fail!("failure", x) }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
