// Copyright 2026 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests the IR output generated by DSLX tracing and implicit tokens in
// functions. The IR is not checked for validity; it is only tested against a
// pre-constructed golden file.

#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/status/status.h"
#include "absl/status/status_matchers.h"
#include "absl/status/statusor.h"
#include "xls/common/file/temp_file.h"
#include "xls/common/status/matchers.h"
#include "xls/common/status/status_macros.h"
#include "xls/dslx/create_import_data.h"
#include "xls/dslx/import_data.h"
#include "xls/dslx/ir_convert/conversion_info.h"
#include "xls/dslx/ir_convert/convert_options.h"
#include "xls/dslx/ir_convert/ir_converter.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/ir_convert/test_utils.h"
#include "xls/dslx/parse_and_typecheck.h"

namespace xls::dslx {
namespace {

using ::absl_testing::IsOkAndHolds;
using ::absl_testing::StatusIs;
using ::testing::HasSubstr;
using ::testing::IsEmpty;
using ::testing::SizeIs;

TEST_F(IrConverterTest, FormatMacroNestedStructArg) {
  constexpr std::string_view program = R"(
struct U32Wrapper {
  v: u32
}

struct Point {
  x: U32Wrapper,
  y: s8,
}

fn main() {
  let p = Point{x: U32Wrapper{v: u32:42}, y: s8:7};
  trace_fmt!("Look! I don't explode *and* I can trace a nested struct: {}", p);
})";

  auto import_data = CreateImportDataForTest();
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(program, "main", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, AssertFmt) {
  constexpr std::string_view program = R"(
fn main(x: u32) -> u32 {
  const VALUE = u32:42;
  assert_fmt!(x != VALUE, "x_is_not_{}", VALUE);
  x
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  EXPECT_THAT(converted, HasSubstr("assert"));
  EXPECT_THAT(converted, HasSubstr("x_is_not_42"));
}

TEST_F(IrConverterTest, TraceFmtSimpleNoArgs) {
  constexpr std::string_view program = R"(fn main() {
    trace_fmt!("Hello world!");
})";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, TraceFmtSimpleWithArgs) {
  constexpr std::string_view program = R"(fn main() {
    let foo = u32:2;
    trace_fmt!("Hello {} {:x}!", "world", foo + u32:1);
})";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, VTraceFmtSimpleNoArgs) {
  constexpr std::string_view program = R"(fn main() {
    vtrace_fmt!(u32:3, "Hello world!");
})";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, VTraceFmtSimpleWithArgs) {
  constexpr std::string_view program = R"(fn main() {
    const VERBOSITY = u32:4;
    let foo = u32:3;
    vtrace_fmt!(VERBOSITY + u32:1, "Hello {} {:x}!", "world", foo + u32:1);
})";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeFunctionWithTraceParametric) {
  constexpr std::string_view program =
      R"(
fn bar<C: u32>() {
  trace_fmt!("C is {}", C);
}

fn foo<A: u32>(x: u32, y: u32) -> u32 {
  bar<A>();
  x + y
}

fn main(x: u32, y: u32) -> u32 {
  foo<u32:1>(x, y)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeFunctionWithTrace) {
  constexpr std::string_view program =
      R"(
fn foo(x: u32, y: u32) -> u32 {
  trace_fmt!("x is {}", x);
  trace_fmt!("y is {}", y);
  x + y
}

fn main(x: u32, y: u32) -> u32 {
  foo(x, y)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ImplicitTokenFalseDoesntClobberTrue) {
  constexpr std::string_view program =
      R"(
fn foo(x: u32) -> u32 {
  trace_fmt!("x is {}", x);
  x
}

fn bar() {}

fn main() {
  bar();
  foo(u32:2);
  bar();
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeFunctionWithTraceInForLoop) {
  constexpr std::string_view program =
      R"(
fn foo(x: u32, y: u32) -> u32 {
  trace_fmt!("x is {}", x);
  trace_fmt!("y is {}", y);
  x + y
}

fn main(x: u32[4]) -> u32[4] {
  for (i, accum): (u32, u32[4]) in u32:0..u32:4 {
    update(x, i, foo(accum[i], x[i]))
  }(x)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
