// Copyright 2026 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests that explicit check the IR output generated by various DSL constructs.
//
// This amounts to whitebox testing of the IR converter end-to-end, whereas DSLX
// tests (i.e. in dslx/tests) are testing functional correctness of results
// (which is more blackbox with respect to the IR conversion process).

#include <string>
#include <string_view>

#include "gtest/gtest.h"
#include "xls/common/status/matchers.h"
#include "xls/dslx/create_import_data.h"
#include "xls/dslx/import_data.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/type_system/typecheck_test_utils.h"

// Tests for lambdas and the "map" function.
namespace xls::dslx {
namespace {

TEST_F(IrConverterTest, MapImportedFunction) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub fn some_function(x: u32) -> u32 { x }
)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn main() -> u32[2] {
  map([u32:1, u32:2], stuff::some_function)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapImportedParametricFunction) {
  auto import_data = CreateImportDataForTest();
  constexpr std::string_view imported_program = R"(
pub fn some_function<N: u32>(x: uN[N]) -> uN[N] { uN[N]:0 }
)";
  XLS_EXPECT_OK(ParseAndTypecheck(imported_program, "fake/imported/stuff.x",
                                  "fake.imported.stuff", &import_data));
  constexpr std::string_view importer_program = R"(
import fake.imported.stuff;

fn main() -> u4[2] {
  map([u4:1, u4:2], stuff::some_function<u32:4>)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(importer_program, kProcScopedChannelOptions,
                           &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapInvocationWithBuiltinFunction) {
  constexpr std::string_view program =
      R"(
fn main(x: u32[4]) -> u32[4] {
  map(x, clz)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapInvocationWithParametricFunction) {
  constexpr std::string_view program =
      R"(
fn f<N:u32, K:u32>(x: u32) -> uN[N] { x as uN[N] + K as uN[N] }

fn main() -> (u5[4], u6[4]) {
  (
    map(u32[4]:[0, 1, 2, 3], f<u32:5, u32:17>),
    map(u32[4]:[0, 1, 2, 3], f<u32:6, u32:3>),
  )
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest,
       MapInvocationWithParametricFunctionFromParametricFunction) {
  constexpr std::string_view program =
      R"(
fn f<N:u32>(x: u32) -> uN[N] { x as uN[N] }

fn g<X:u32>(x: u32) -> uN[X][3] { map([x, x + u32:1, x + u32:2], f<X>) }

fn main() -> (u5[3], u6[3]) {
  (
    g<u32:5>(u32:1),
    g<u32:6>(u32:2),
  )
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapInvocationWithImplicitToken) {
  constexpr std::string_view program =
      R"(
fn f(x: u32) -> u64 {
    assert!(x != u32:42, "foobar");
    u16:0 ++ x ++ u16:4
}

fn main() -> u64[4] {
    map(u32[4]:[0, 1, 2, 3], f)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambda) {
  constexpr std::string_view kModule = R"(
fn add_five(arr: u32[4]) -> u32[4] {
  let x = u32:5;
  map(arr, | i | -> u32 { i + x })
}

fn main() -> u32 {
  add_five(u32:0..4)[1]
}

const_assert!(main() == 6);
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kModule));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambdaWithParentParametric) {
  constexpr std::string_view kModule = R"(
fn add_five<N: u32>(arr: u32[4]) -> uN[N][4] {
  let x = uN[N]:5;
  map(arr, | i | { i as uN[N] + x })
}

fn main() -> u16 {
  add_five<16>(u32:0..4)[1]
}

const_assert!(main() == 6);
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kModule));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambdaImplicitReturn) {
  constexpr std::string_view kModule = R"(
fn add_five(arr: u32[4]) -> u32[4] {
  let x = u32:5;
  map(arr, | i | { i + x })
}

fn main() -> u32 {
  add_five(u32:0..4)[1]
}

const_assert!(main() == 6);
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kModule));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambdaWithParentParametricCallsFn) {
  constexpr std::string_view kModule = R"(
fn add<N: u32>(val: u32, delta: uN[N]) -> uN[N] {
  val as uN[N] + delta
}

fn use_lambda<N: u32>(arr: u32[4]) -> uN[N][4] {
  let x = uN[N]:5;
  map(arr, | i | -> uN[N] { add<N>(i, x) })
}

fn main() -> u16 {
  use_lambda<16>(u32:0..4)[1]
}

const_assert!(main() == 6);
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kModule));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambdaWithImplicitToken) {
  constexpr std::string_view program =
      R"(
fn f(x: u32) -> u64 {
    assert!(x != u32:42, "foobar");
    u16:0 ++ x ++ u16:4
}

fn main() -> u64[4] {
    map(u32[4]:[0, 1, 2, 3], |i| -> u64 { f(i) })
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NestedLambdasWithVariables) {
  constexpr std::string_view program =
      R"(
const X = u32:2;
const Y = u32:3;
type word = u4;
type Results = word[X][Y];

fn nested() -> Results {
  let used_in_outer = [[false, false], [true, true], [true, false]];
  map(0..Y, | y_idx: u32 | -> word[X] {
      let used_in_inner = used_in_outer[y_idx];
      map(0..X, | x_idx: u32 | -> word {
          if used_in_inner[x_idx] {
              1
          } else {
              0
          }
      })
  })
}

fn main() -> Results {
  nested()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NestedLambdasWithVariablesInFor) {
  constexpr std::string_view program =
      R"(
const X = u32:2;
const Y = u32:3;
const COUNT = u32:4;
type word = u4;
type Results = word[X][Y];

fn nested() -> Results {
  let used_in_outer = [[false, false], [true, true], [true, false], [false, false]];
  for (ct, result): (u32, Results) in u32:0..COUNT {
      map(result, | res | -> word[X] {
          let used_in_inner = used_in_outer[0];
          map(0..X, | x_idx | -> word {
              if used_in_inner[x_idx] {
                  1
              } else {
                  0
              }
          })
      })
  }(zero!<Results>())
}

fn main() -> Results {
  nested()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapInvocationWithStruct) {
  constexpr std::string_view program =
      R"(
struct Foo { x: u32, y: u32 }
struct Bar { a: u16, b: u16, c: u32 }
fn f(x: Foo) -> Bar {
    assert!(x.x != u32:42, "foobar");
    Bar { a: x.x[0+:u16], b: x.x[16+:u16], c: x.y }
}

fn main(lst: Foo[u32:6]) -> Bar[u32:6] {
    map(lst, f)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapArrayElementInstanceMethod) {
  constexpr std::string_view program =
      R"(
struct S {
  x: u32
}

impl S {
  fn plus1(self) -> u32 {
    self.x + 1
  }
}

fn main() -> u32[3] {
  map([S { x: 10 }, S { x: 1 }, S { x: 5 }], S::plus1)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapStaticImplFunction) {
  constexpr std::string_view program =
      R"(
struct S {}

impl S {
  fn plus1(x: u32) -> u32 {
    x + 1
  }
}

fn main() -> u32[3] {
  map([u32:10, 1, 5], S::plus1)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapAuxiliaryObjectFunction) {
  constexpr std::string_view program =
      R"(
struct S {
  x: u32
}

impl S {
  fn plus(self, y: u32) -> u32 {
    self.x + y
  }
}

fn main() -> u32[3] {
  let inst = S { x: 10 };
  map([u32:10, 1, 5], inst.plus)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
