// Copyright 2021 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests the IR output generated by DSLX builtin operations (fail, cover,
// assert, gate, range, signex, mulp) and map invocations. The IR is not checked
// for validity; it is only tested against a pre-constructed golden file.

#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/status/status.h"
#include "absl/status/status_matchers.h"
#include "absl/status/statusor.h"
#include "xls/common/file/temp_file.h"
#include "xls/common/status/matchers.h"
#include "xls/dslx/create_import_data.h"
#include "xls/dslx/import_data.h"
#include "xls/dslx/ir_convert/conversion_info.h"
#include "xls/dslx/ir_convert/convert_options.h"
#include "xls/dslx/ir_convert/ir_converter.h"
#include "xls/dslx/ir_convert/ir_converter_test_utils.h"
#include "xls/dslx/type_system/typecheck_test_utils.h"

namespace xls::dslx {
namespace {

using ::absl_testing::IsOkAndHolds;
using ::absl_testing::StatusIs;
using ::testing::HasSubstr;

TEST_F(IrConverterTest, ExtendConversions) {
  constexpr std::string_view program =
      R"(fn main(x: u8, y: s8) -> (u32, u32, s32, s32) {
  (x as u32, y as u32, x as s32, y as s32)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeNullary) {
  constexpr std::string_view program =
      R"(fn callee() -> u32 {
  u32:42
}
fn caller() -> u32 {
  callee()
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, BoolLiterals) {
  constexpr std::string_view program =
      R"(
fn f(x: u8) -> bool {
  if x == u8:42 { true } else { false }
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConstexprFunction) {
  constexpr std::string_view program =
      R"(
const MY_CONST = u32:5;
fn constexpr_fn(arg: u32) -> u32 {
  arg * MY_CONST
}

fn f() -> u32 {
  let x = constexpr_fn(MY_CONST);
  x
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, Identity) {
  constexpr std::string_view program =
      R"(fn main(x: u8) -> u8 {
  x
})";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParametricIrConversion) {
  constexpr std::string_view program =
      R"(
fn parametric<N: u32>(x: bits[N]) -> u32 {
  N
}

fn main() -> u32 {
  parametric(bits[2]:0) + parametric(bits[3]:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UnconditionalFail) {
  constexpr std::string_view program = R"(
fn main() -> u32 {
  fail!("failure", u32:42)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeMethodThatFails) {
  constexpr std::string_view program = R"(
fn does_fail() -> u32 {
  fail!("failure", u32:42)
}

fn main(x: u32) -> u32 {
  does_fail()
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeParametricThatFails) {
  constexpr std::string_view program = R"(
fn does_fail<N: u32>() -> bits[N] {
  fail!("failure", bits[N]:42)
}

fn main(x: u32) -> u32 {
  does_fail<u32:32>()
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeParametricThatInvokesFailing) {
  constexpr std::string_view program = R"(
fn does_fail() -> u32 {
  fail!("failure", u32:42)
}

fn calls_failing<N: u32>() -> bits[N] {
  does_fail()
}

fn main(x: u32) -> u32 {
  calls_failing<u32:32>()
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SignedComparisonsViaSignedNumbers) {
  constexpr std::string_view program =
      R"(
fn main(x: s32, y: s32) -> bool {
  x > y && x < y && x >= y && x <= y
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParametricConstexprFn) {
  constexpr std::string_view program =
      R"(
pub const MY_CONST = u32:5;
fn constexpr_fn<N:u32>(arg: bits[N]) -> bits[N] {
  arg * MY_CONST
}

fn f() -> u32 {
  let x = constexpr_fn(MY_CONST);
  x
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertCoverOp) {
  constexpr std::string_view program = R"(
fn main(x: u32, y: u32) {
  let foo = x == y;
  cover!("x_equals_y", foo)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertCoverOpWithConditionalGuard) {
  constexpr std::string_view program = R"(
fn f(x: u32) -> u32 {
    cover!("x_less_than_0", x < u32:0);
    x
}

fn main(y: u32) -> u32 {
    if y < u32:10 {
        f(y)
    } else {
        u32:0
    }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertAssertOpWithConditionalGuard) {
  constexpr std::string_view program = R"(
fn f(x: u32) -> u32 {
    assert!(x < u32:5, "x_less_than_5");
    x
}

fn main(y: u32) -> u32 {
    if y < u32:10 {
        f(y)
    } else {
        u32:0
    }
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertGateOp) {
  constexpr std::string_view program = R"(
fn main(p: bool, x: u32) -> u32 {
  gate!(p, x)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertRangeOpUnsigned) {
  constexpr std::string_view program = R"(
fn main() -> u32[5] {
  u32:2..u32:7
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertRangeOpSigned) {
  constexpr std::string_view program = R"(
fn main() -> s32[4] {
  s32:-2..s32:2
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertRangeOpUnsignedInclusiveEnd) {
  constexpr std::string_view program = R"(
fn main() -> u4[16] {
  u4:0..=u4:15
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertRangeOpSignedInclusiveEnd) {
  constexpr std::string_view program = R"(
fn main() -> s4[16] {
  s4:-8..=s4:7
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertRangeOpInclusiveEndSameValue) {
  constexpr std::string_view program = R"(
fn main() -> s32[1] {
  s32:0x80000000..=s32:0x80000000
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, PublicFnGetsTokenWrapper) {
  constexpr std::string_view program = R"(
fn callee_callee(x:u32) -> u32 {
  fail!("failure", x > u32:3);
  x
}

pub fn main(x:u32) -> u32 {
  callee_callee(x)
}

fn callee(x:u32) -> u32 {
  main(x)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NonpublicFnDoesNotGetTokenWrapper) {
  constexpr std::string_view program = R"(
fn callee_callee(x:u32) -> u32 {
  fail!("failure", x > u32:3);
  x
}

fn main(x:u32) -> u32 {
  callee_callee(x)
}

fn callee(x:u32) -> u32 {
  main(x)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, Signex) {
  constexpr std::string_view program =
      R"(
fn main(x: u8) -> u32 {
  signex(x, u32:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SMulp) {
  constexpr std::string_view program = R"(
fn main(x: s10, y: s10) -> s10 {
  let product = smulp(x, y);
  let sum = product.0 + product.1;
  sum as s10
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, UMulp) {
  constexpr std::string_view program = R"(
fn main(x: u10, y: u10) -> u10 {
  let product = umulp(x, y);
  product.0 + product.1
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, OneHotSelSplat) {
  constexpr std::string_view program =
      R"(
fn main(s: u2) -> u32 {
  one_hot_sel(s, u32[2]:[2, 3])
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, OneHotSelNonArrayNode) {
  // Tests that the cases parameter of a one_hot_sel can take a node that
  // is not an Array node, but rather a name that refers to an Array.
  //
  // See https://github.com/google/xls/issues/1303
  constexpr std::string_view program =
      R"(
fn main(s: u2) -> u32 {
  let cases = u32[2]:[2, 3];
  one_hot_sel(s, cases)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, PrioritySelSplat) {
  constexpr std::string_view program =
      R"(
fn main(s: u2) -> u32 {
  priority_sel(s, u32[2]:[u32:2, u32:3], u32:4)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, StringWithUnsignedRangeCharacter) {
  constexpr std::string_view program = R"(fn main() -> u8[1] {
  "\x80"  // -128 in signed char interpretation
})";

  auto import_data = CreateImportDataForTest();
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(program, "main", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, WideningCastsUnErrors) {
  constexpr std::string_view program =
      R"(
fn main(x: u8) -> u32 {
  let x_32 = widening_cast<u32>(x);
  let x_4  = widening_cast<u4>(x_32);
  x_32 + widening_cast<u32>(x_4)
}
)";

  auto import_data = CreateImportDataForTest();
  EXPECT_THAT(ConvertOneFunctionForTest(program, "main", import_data),
              StatusIs(absl::StatusCode::kInvalidArgument,
                       HasSubstr("Cannot cast from type `uN[32]` (32 bits) "
                                 "to `uN[4]` (4 bits) with widening_cast")));
}

TEST_F(IrConverterTest, WideningAndCheckedCasts) {
  constexpr std::string_view program =
      R"(
fn main(x: u8, y: s8) -> u32 {
  let x_32 = checked_cast<u32>(widening_cast<u32>(x));
  let y_16 = widening_cast<s16>(checked_cast<s7>(y));
  let y_times_two_32 = checked_cast<s32>(y_16) + widening_cast<s32>(y_16);
  x_32 + checked_cast<u32>(y_times_two_32)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ArraySizeBuiltin) {
  constexpr std::string_view program =
      R"(
fn main(x: u8[42]) -> u32 {
  array_size(x)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, BitCount) {
  constexpr std::string_view program = R"(
struct S {
  a: u32
}

struct T<N: u32> {
  a: uN[N]
}

fn main() -> u32 {
  bit_count<u32>() +
  bit_count<s64>() +
  bit_count<u32[u32:4]>() +
  bit_count<bool>() +
  bit_count<S>() +
  bit_count<T<u32:4>>() +
  bit_count<(u32, bool)>()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ElementCount) {
  constexpr std::string_view program = R"(
struct S {
  a: u32,
  b: u32
}

struct T<N: u32> {
  a: uN[N]
}

fn main() -> u32 {
  element_count<u32>() +
  element_count<s64>() +
  element_count<u32[u32:4]>() +
  element_count<u32[u32:4][u32:5]>() +
  element_count<bool>() +
  element_count<S>() +
  element_count<T<u32:4>>() +
  element_count<(u32, bool)>()
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConfiguredValue) {
  constexpr std::string_view program = R"(
enum MyEnum : u2 {
  A = 0,
  B = 1,
  C = 2,
}

fn main() -> (bool, u32, s32, MyEnum, bool, u32, s32, MyEnum) {
  let b_default = configured_value_or<bool>("b_default", false);
  let u_default = configured_value_or<u32>("u32_default", u32:42);
  let s_default = configured_value_or<s32>("s32_default", s32:-100);
  let e_default = configured_value_or<MyEnum>("enum_default", MyEnum::C);
  let b_override = configured_value_or<bool>("b_override", false);
  let u_override = configured_value_or<u32>("u32_override", u32:42);
  let s_override = configured_value_or<s32>("s32_override", s32:-100);
  let e_override = configured_value_or<MyEnum>("enum_override", MyEnum::C);
  (b_default, u_default, s_default, e_default, b_override, u_override, s_override, e_override)
}
)";
  ConvertOptions options;
  options.configured_values = {"b_override:true", "u32_override:123",
                               "s32_override:-200", "enum_override:MyEnum::B"};
  options.emit_positions = false;
  options.lower_to_proc_scoped_channels = true;
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program, options));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConfiguredValueBoolFalse) {
  constexpr std::string_view program = R"(
fn main() -> bool {
  configured_value_or<bool>("val", true)
}
)";
  ConvertOptions options;
  options.configured_values = {"val:false"};
  options.emit_positions = false;
  options.lower_to_proc_scoped_channels = true;
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program, options));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConfiguredValueBoolTrue) {
  constexpr std::string_view program = R"(
fn main() -> bool {
  configured_value_or<bool>("val", false)
}
)";
  ConvertOptions options;
  options.configured_values = {"val:true"};
  options.emit_positions = false;
  options.lower_to_proc_scoped_channels = true;
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program, options));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConfiguredValueBoolZero) {
  constexpr std::string_view program = R"(
fn main() -> bool {
  configured_value_or<bool>("val", true)
}
)";
  ConvertOptions options;
  options.configured_values = {"val:0"};
  options.emit_positions = false;
  options.lower_to_proc_scoped_channels = true;
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program, options));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConfiguredValueBoolOne) {
  constexpr std::string_view program = R"(
fn main() -> bool {
  configured_value_or<bool>("val", false)
}
)";
  ConvertOptions options;
  options.configured_values = {"val:1"};
  options.emit_positions = false;
  options.lower_to_proc_scoped_channels = true;
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program, options));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConfiguredValueBoolTwo) {
  constexpr std::string_view program = R"(
fn main() -> bool {
  configured_value_or<bool>("val", false)
}
)";
  ConvertOptions options;
  options.configured_values = {"val:2"};
  options.emit_positions = false;
  options.lower_to_proc_scoped_channels = true;
  EXPECT_THAT(ConvertModuleForTest(program, options),
              StatusIs(absl::StatusCode::kInvalidArgument));
}

TEST_F(IrConverterTest, ConfiguredValueBoolMinus1) {
  constexpr std::string_view program = R"(
fn main() -> bool {
  configured_value_or<bool>("val", true)
}
)";
  ConvertOptions options;
  options.configured_values = {"val:-1"};
  options.emit_positions = false;
  options.lower_to_proc_scoped_channels = true;
  EXPECT_THAT(ConvertModuleForTest(program, options),
              StatusIs(absl::StatusCode::kInvalidArgument));
}

TEST_F(IrConverterTest, ConfiguredValueBoolBogus) {
  constexpr std::string_view program = R"(
fn main() -> bool {
  configured_value_or<bool>("val", false)
}
)";
  ConvertOptions options;
  options.configured_values = {"val:foobar"};
  options.emit_positions = false;
  options.lower_to_proc_scoped_channels = true;
  EXPECT_THAT(ConvertModuleForTest(program, options),
              StatusIs(absl::StatusCode::kInvalidArgument));
}

TEST_F(IrConverterTest, MapInvocationWithBuiltinFunction) {
  constexpr std::string_view program =
      R"(
fn main(x: u32[4]) -> u32[4] {
  map(x, clz)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapInvocationWithParametricFunction) {
  constexpr std::string_view program =
      R"(
fn f<N:u32, K:u32>(x: u32) -> uN[N] { x as uN[N] + K as uN[N] }

fn main() -> (u5[4], u6[4]) {
  (
    map(u32[4]:[0, 1, 2, 3], f<u32:5, u32:17>),
    map(u32[4]:[0, 1, 2, 3], f<u32:6, u32:3>),
  )
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest,
       MapInvocationWithParametricFunctionFromParametricFunction) {
  constexpr std::string_view program =
      R"(
fn f<N:u32>(x: u32) -> uN[N] { x as uN[N] }

fn g<X:u32>(x: u32) -> uN[X][3] { map([x, x + u32:1, x + u32:2], f<X>) }

fn main() -> (u5[3], u6[3]) {
  (
    g<u32:5>(u32:1),
    g<u32:6>(u32:2),
  )
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapInvocationWithImplicitToken) {
  constexpr std::string_view program =
      R"(
fn f(x: u32) -> u64 {
    assert!(x != u32:42, "foobar");
    u16:0 ++ x ++ u16:4
}

fn main() -> u64[4] {
    map(u32[4]:[0, 1, 2, 3], f)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambda) {
  constexpr std::string_view kModule = R"(
fn add_five(arr: u32[4]) -> u32[4] {
  let x = u32:5;
  map(arr, | i | -> u32 { i + x })
}

fn main() -> u32 {
  add_five(u32:0..4)[1]
}

const_assert!(main() == 6);
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kModule));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambdaWithParentParametric) {
  constexpr std::string_view kModule = R"(
fn add_five<N: u32>(arr: u32[4]) -> uN[N][4] {
  let x = uN[N]:5;
  map(arr, | i | { i as uN[N] + x })
}

fn main() -> u16 {
  add_five<16>(u32:0..4)[1]
}

const_assert!(main() == 6);
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kModule));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambdaImplicitReturn) {
  constexpr std::string_view kModule = R"(
fn add_five(arr: u32[4]) -> u32[4] {
  let x = u32:5;
  map(arr, | i | { i + x })
}

fn main() -> u32 {
  add_five(u32:0..4)[1]
}

const_assert!(main() == 6);
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kModule));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambdaWithParentParametricCallsFn) {
  constexpr std::string_view kModule = R"(
fn add<N: u32>(val: u32, delta: uN[N]) -> uN[N] {
  val as uN[N] + delta
}

fn use_lambda<N: u32>(arr: u32[4]) -> uN[N][4] {
  let x = uN[N]:5;
  map(arr, | i | -> uN[N] { add<N>(i, x) })
}

fn main() -> u16 {
  use_lambda<16>(u32:0..4)[1]
}

const_assert!(main() == 6);
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(kModule));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapLambdaWithImplicitToken) {
  constexpr std::string_view program =
      R"(
fn f(x: u32) -> u64 {
    assert!(x != u32:42, "foobar");
    u16:0 ++ x ++ u16:4
}

fn main() -> u64[4] {
    map(u32[4]:[0, 1, 2, 3], |i| -> u64 { f(i) })
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapInvocationWithStruct) {
  constexpr std::string_view program =
      R"(
struct Foo { x: u32, y: u32 }
struct Bar { a: u16, b: u16, c: u32 }
fn f(x: Foo) -> Bar {
    assert!(x.x != u32:42, "foobar");
    Bar { a: x.x[0+:u16], b: x.x[16+:u16], c: x.y }
}

fn main(lst: Foo[u32:6]) -> Bar[u32:6] {
    map(lst, f)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapArrayElementInstanceMethod) {
  constexpr std::string_view program =
      R"(
struct S {
  x: u32
}

impl S {
  fn plus1(self) -> u32 {
    self.x + 1
  }
}

fn main() -> u32[3] {
  map([S { x: 10 }, S { x: 1 }, S { x: 5 }], S::plus1)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapStaticImplFunction) {
  constexpr std::string_view program =
      R"(
struct S {}

impl S {
  fn plus1(x: u32) -> u32 {
    x + 1
  }
}

fn main() -> u32[3] {
  map([u32:10, 1, 5], S::plus1)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, MapAuxiliaryObjectFunction) {
  constexpr std::string_view program =
      R"(
struct S {
  x: u32
}

impl S {
  fn plus(self, y: u32) -> u32 {
    self.x + y
  }
}

fn main() -> u32[3] {
  let inst = S { x: 10 };
  map([u32:10, 1, 5], inst.plus)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConvertFilesToPackageFailsTypeCheck) {
  constexpr std::string_view program =
      R"(
fn main() -> u8 {
  u32:0
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(xls::TempFile temp,
                           xls::TempFile::CreateWithContent(program, ".x"));
  const std::string dslx_str_path = temp.path().string();
  bool printed_error = false;
  absl::StatusOr<PackageConversionData> result = ConvertFilesToPackage(
      {dslx_str_path},
      /*stdlib_path=*/"", {temp.path()}, kProcScopedChannelOptions,
      /*top=*/"main",
      /*package_name=*/std::nullopt, &printed_error);
  EXPECT_THAT(result, StatusIs(absl::StatusCode::kInvalidArgument,
                               HasSizeMismatch("u32", "u8")));
}

TEST_F(IrConverterTest, GenericTypePassthroughFunction) {
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted, ConvertModuleForTest(R"(
#![feature(generics)]

struct S { a: u32 }

fn foo<T: type>(a: T) -> T { a }

type MyInt = u34;

enum MyEnum { A = 0 }

fn main() {
  const C = foo<u32>(5);
  const D = foo<u16[3]>([1, 2, 3]);
  const E = foo((s8:5, s8:6));
  const F = foo<S>(S { a: 5 });
  const G = foo<MyInt>(10);
  const H = foo(MyEnum::A);
}
)"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SquareAnythingFunction) {
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted, ConvertModuleForTest(R"(
#![feature(generics)]

fn square<T: type>(a: T) -> T { a * a }

fn main() -> (u32, s64) {
  (square(u32:5), square<s64>(-12))
}
)"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, OptionalStruct) {
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted, ConvertModuleForTest(R"(
#![feature(generics)]

struct Optional<T: type> {
  has_value: bool,
  value: T
}

fn make_optional<T: type>(value: T) -> Optional<T> {
  Optional<T> { has_value: true, value: value }
}

fn make_nullopt<T: type>() -> Optional<T> {
  zero!<Optional<T>>()
}

fn main() -> (Optional<u32>, Optional<u32>, Optional<u32[3]>,
              Optional<Optional<u32>>) {
  (make_optional(u32:5),
   make_nullopt<u32>(),
   make_optional<u32[3]>([1, 2, 3]),
   make_optional(make_optional(u32:5)))
}
)"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CallFooOnAnything) {
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted, ConvertModuleForTest(R"(
#![feature(generics)]

struct U32Wrapper { a: u32 }
struct S64Wrapper { a: s64 }

impl U32Wrapper {
  fn foo(self) -> u32 { self.a + 5 }
}

impl S64Wrapper {
  fn foo(self) -> s64 { self.a * self.a }
}

fn call_foo<R: type, T: type>(value: T) -> R {
  value.foo()
}

fn main() -> (u32, s64) {
  (call_foo<u32>(U32Wrapper { a: 10 }), call_foo<s64>(S64Wrapper { a: -2 }))
}
)"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ToBits) {
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted, ConvertModuleForTest(R"(
enum E : u16 {
  X = 1
}

#[derive(ToBits)]
struct Bar {
  data: u32
}

struct Baz {
  x: u24,
  y: u24
}

impl Baz {
  fn to_bits(self) -> u48 { self.y ++ self.x }
}

#[derive(ToBits)]
struct Foo {
  a: u32,
  b: s64,
  c: u8[3],
  d: (u8, u8),
  e: E,
  f: Bar,
  g: Baz
}

fn main() -> bits[bit_count<Foo>()] {
  let f = Foo {
    a: 5,
    b: -1,
    c: [10, 11, 12],
    d: (1, 2),
    e: E::X,
    f: Bar { data: 100 },
    g: Baz { x: 1, y: 2 }
  };

  f.to_bits()
}
)"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, CastOfAdd) {
  constexpr std::string_view program =
      R"(
fn main(x: u8, y: u8) -> u32 {
  (x + y) as u32
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ConstantInFn) {
  constexpr std::string_view program = R"(
fn f(input: u16) -> u16 {
  all_ones!<u16>() + input
}

fn main() -> u16 {
  f(u16:1)
}
)";

  auto import_data = CreateImportDataForTest();
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "main"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FunctionCallProcessed) {
  ImportData import_data = CreateImportDataForTest();
  constexpr std::string_view fake_std_lib = R"(
pub fn pow<S: bool, N: u32>(x: xN[S][N], n: uN[N]) -> xN[S][N] {
    let result = xN[S][N]:1;
    let p = x;

    let work = for (i, (n, p, result)) in u32:0..N {
        let result = if (n & uN[N]:1) == uN[N]:1 { result * p } else { result };
        (n >> 1, if n == uN[N]:0 { p } else { p * p }, result)
    }((n, p, result));
    work.2
}

pub fn clog2<N: u32>(x: bits[N]) -> bits[N] {
    if x >= bits[N]:1 { (N as bits[N]) - clz(x - bits[N]:1) } else { bits[N]:0 }
}

pub fn upow<N: u32>(x: uN[N], n: uN[N]) -> uN[N] { pow(x, n) }

pub fn next_pow2(n: u32) -> u32 {
    upow(u32:2, clog2(n))
}
)";
  XLS_EXPECT_OK(
      ParseAndTypecheck(fake_std_lib, "fake_std.x", "fake_std", &import_data));

  constexpr std::string_view test_program = R"(
import fake_std;

#[test]
pub fn test_next_pow2() {
    assert_eq(fake_std::next_pow2(u32:1), u32:1);
}

)";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(
          test_program,
          ConvertOptions{.emit_positions = false,
                         .emit_assert = true,
                         .verify_ir = false,
                         .convert_tests = true,
                         .lower_to_proc_scoped_channels = true},
          &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, IdentityFinalArg) {
  constexpr std::string_view program =
      R"(
fn main(x0: u19, x3: u29) -> u29 {
  let x15: u29 = u29:0;
  let x17: u19 = (x0) + (x15 as u19);
  x3
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvocationMultiSymbol) {
  constexpr std::string_view program =
      R"(fn parametric<M: u32, N: u32, R: u32 = {M + N}>(x: bits[M], y: bits[N]) -> bits[R] {
  x ++ y
}
fn main() -> u8 {
  parametric(bits[3]:0, bits[5]:1)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, InvokeMultipleArgs) {
  constexpr std::string_view program =
      R"(fn callee(x: bits[32], y: bits[32]) -> bits[32] {
  x + y
}
fn caller() -> u32 {
  callee(u32:2, u32:3)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NonSynthNoAssert) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let x = u32:42;
  assert!(x > u32:11, "bang");
  x
})";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(
          program, "f",
          ConvertOptions{.emit_assert = false,
                         .lower_to_proc_scoped_channels = true}));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NonSynthNoCover) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let x = u32:42;
  cover!("bang", x > u32:11);
  x
})";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(
          program, "f",
          ConvertOptions{.emit_cover = false,
                         .lower_to_proc_scoped_channels = true}));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, NonSynthNoTrace) {
  constexpr std::string_view program =
      R"(fn f() -> u32 {
  let x = u32:42;
  trace_fmt!("bang {}", x);
  x
})";
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(
          program, "f",
          ConvertOptions{.emit_trace = false,
                         .lower_to_proc_scoped_channels = true}));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParameterShadowingModuleLevelConstant) {
  constexpr std::string_view program = R"(
  const FOO = u32:0;

  fn test1<FOO:u32>(x:u32) -> u32 {
    x + FOO
  }

  fn test2<FOO:u32>(x:u32) -> u32 {
    test1<FOO>(x) - FOO
  }

  fn main() -> u32 {
    let foo = test2<u32:3>(u32:3);
    foo
  }
  )";

  auto import_data = CreateImportDataForTest();
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertModuleForTest(program, kProcScopedChannelOptions, &import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParametricConstantInFn) {
  constexpr std::string_view program = R"(
fn f<N:u32>(input: uN[N]) -> uN[N] {
  all_ones!<uN[N]>() + input
}

fn main() -> u16 {
  f<u32:16>(u16:1)
}
)";

  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertOneFunctionForTest(program, "main"));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, ParametricInvocation) {
  constexpr std::string_view program =
      R"(
fn parametric_id<N: u32>(x: bits[N]) -> bits[N] {
  x+(N as bits[N])
}

fn main(x: u8) -> u8 {
  parametric_id(x)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, PrioritySelNonArrayNode) {
  // Tests that the cases parameter of a priority_sel can take a node that
  // is not an Array node, but rather a name that refers to an Array.
  //
  // See https://github.com/google/xls/issues/1303

  constexpr std::string_view program =
      R"(
fn main(s: u2) -> u32 {
  let cases = u32[2]:[2, 3];
  priority_sel(s, cases, u32:4)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, SignexAcceptsSignedOutputType) {
  constexpr std::string_view program =
      R"(
fn main(x: u8) -> s32 {
  signex(x, s32:0)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, TransitiveParametricInvocation) {
  constexpr std::string_view program =
      R"(
fn parametric_id<N: u32>(x: bits[N]) -> bits[N] {
  x+(N as bits[N])
}
fn parametric_id_wrapper<M: u32>(x: bits[M]) -> bits[M] {
  parametric_id(x)
}
fn main(x: u8) -> u8 {
  parametric_id_wrapper(x)
}
)";
  XLS_ASSERT_OK_AND_ASSIGN(std::string converted,
                           ConvertModuleForTest(program));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, TypeErrorInUninstantiatedParametric) {
  constexpr std::string_view program = R"(fn f<N: u32>(x: u8) -> u8 { 42(x) })";
  absl::StatusOr<std::string> converted = ConvertModuleForTest(program);
  EXPECT_THAT(converted, IsOkAndHolds("package test_module\n"));
}

TEST_F(IrConverterTest, FormatMacro) {
  constexpr std::string_view program = R"(fn main() {
  trace_fmt!("Look! I don't explode!");
})";

  auto import_data = CreateImportDataForTest();
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(program, "main", import_data));
  ExpectIr(converted);
}

TEST_F(IrConverterTest, FormatMacroStructArg) {
  constexpr std::string_view program = R"(
struct Point {
  x: u32,
  y: s8,
}

fn main() {
  let p = Point{x: u32:42, y: s8:7};
  trace_fmt!("Look! I don't explode *and* I can trace a struct: {}", p);
})";

  auto import_data = CreateImportDataForTest();
  XLS_ASSERT_OK_AND_ASSIGN(
      std::string converted,
      ConvertOneFunctionForTest(program, "main", import_data));
  ExpectIr(converted);
}

}  // namespace
}  // namespace xls::dslx
