// Copyright 2026 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_SOLVERS_SYMEX_TEST_UTIL_H_
#define XLS_SOLVERS_SYMEX_TEST_UTIL_H_

#include <cstdint>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/str_cat.h"
#include "absl/types/span.h"
#include "xls/common/status/status_macros.h"
#include "xls/ir/function.h"
#include "xls/ir/ir_test_base.h"
#include "xls/ir/value.h"
#include "xls/solvers/symex/symbolic_path.h"
#include "z3/src/api/z3.h"  // IWYU pragma: keep
#include "z3/src/api/z3_api.h"

namespace xls::solvers::symex {

// Base fixture for symbolic execution unit tests managing Z3 context lifecycle.
class SymExTestBase : public IrTestBase {
 protected:
  void SetUp() override {
    IrTestBase::SetUp();
    config_ = Z3_mk_config();
    ctx_ = Z3_mk_context(config_);
  }

  void TearDown() override {
    if (ctx_ != nullptr) {
      Z3_del_context(ctx_);
    }
    if (config_ != nullptr) {
      Z3_del_config(config_);
    }
    IrTestBase::TearDown();
  }

  Z3_config config_ = nullptr;
  Z3_context ctx_ = nullptr;
};

// Returns true if cond1 and cond2 are mutually exclusive (i.e. check(cond1 &&
// cond2) == UNSAT).
bool AreMutuallyExclusive(Z3_context ctx, Z3_ast cond1, Z3_ast cond2);

// Returns true if the disjunction of all path conditions covers 100% of the
// input domain (i.e. check(!combined_path_condition) == UNSAT).
bool IsExhaustiveCoverage(Z3_context ctx, absl::Span<const SymbolicPath> paths);

// Returns true if paths form a complete partition (pairwise mutually exclusive
// and collectively exhaustive).
bool VerifyCompletePartition(Z3_context ctx,
                             absl::Span<const SymbolicPath> paths);

// Evaluates the function using the witness concrete inputs from the path.
absl::StatusOr<Value> InterpretPath(Function* fn, const SymbolicPath& path);

// Combines a set of mutually exclusive, exhaustive symbolic paths into a
// single nested if-then-else (ite) AST tree:
//   ite(G_0, Y_0, ite(G_1, Y_1, ... Y_{N-1}))
Z3_ast CombinePathsToIte(Z3_context ctx, absl::Span<const SymbolicPath> paths);

// Returns true if the piecewise if-then-else (ite) combination of symbolic
// path return values is logically equivalent to the monolithic circuit
// translation generated by IrTranslator across the entire input domain.
bool CheckSmtEncodingEquivalence(Z3_context ctx, Function* fn,
                                 absl::Span<const SymbolicPath> paths);

// Signature for domain-specific reference oracle validation functions.
using OracleFn = std::function<absl::Status(const SymbolicPath& path,
                                            const Value& interp_result)>;

// Configuration specifying which formal properties to verify on symbolic paths.
struct FormalCheckConfig {
  // Check that every pair of paths has disjoint conditions (SAT(G_i && G_j) ==
  // UNSAT).
  bool check_mutual_exclusivity = true;

  // Check that path conditions cover 100% of the input domain (SAT(!or_k G_k)
  // == UNSAT).
  bool check_exhaustiveness = true;

  // Check that the combined ITE tree equals the monolithic IrTranslator model.
  bool check_smt_ite_equivalence = true;

  // Check that witness test inputs execute successfully in FunctionInterpreter.
  bool check_witness_interpretation = true;

  // Expected number of explored paths (nullopt to skip check).
  std::optional<int64_t> expected_paths = std::nullopt;

  // Optional domain-specific oracle function to validate witness execution
  // results.
  OracleFn oracle = nullptr;
};

// Verifies the configured formal properties on `paths` for `func`.
// Usable by both unit tests (in-memory IR / FunctionBuilder) and e2e tests.
absl::Status CheckFormalProperties(Z3_context ctx, Function* func,
                                   absl::Span<const SymbolicPath> paths,
                                   const FormalCheckConfig& config = {});

// Helper to run path exploration with `EngineT` on `func` and verify configured
// formal properties.
template <typename EngineT>
absl::Status ExploreAndVerifyFunction(Z3_context ctx, Function* func,
                                      const FormalCheckConfig& config = {}) {
  XLS_ASSIGN_OR_RETURN(EngineT engine, EngineT::Create(ctx));
  XLS_ASSIGN_OR_RETURN(std::vector<SymbolicPath> paths,
                       engine.ExplorePaths(func));
  return CheckFormalProperties(ctx, func, paths, config);
}

// Matcher for BranchDecision checking arm_index and is_default.
MATCHER_P2(BranchDecisionIs, arm_index, is_default,
           absl::StrCat("has arm_index ", arm_index, " and is_default ",
                        is_default ? "true" : "false")) {
  return arg.arm_index == arm_index && arg.is_default() == is_default;
}

// Matcher for a single-decision SymbolicPath checking its first branch
// decision.
MATCHER_P2(SymbolicPathIs, arm_index, is_default,
           absl::StrCat("has first decision arm_index ", arm_index,
                        " and is_default ", is_default ? "true" : "false")) {
  if (arg.branch_decisions.empty()) {
    *result_listener << "has empty branch_decisions";
    return false;
  }
  const auto& decision = arg.branch_decisions[0];
  return decision.arm_index == arm_index && decision.is_default() == is_default;
}

}  // namespace xls::solvers::symex

#endif  // XLS_SOLVERS_SYMEX_TEST_UTIL_H_
