repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: '^(xls/contrib/.*|docs_src/bazel_rules_macros.md|.*\.(sh|ir|txt|patch|csv))$'
  - repo: local
    hooks:
      - id: check-cpp-absolute-includes
        name: Check C++ absolute includes
        entry: xls/dev_tools/check_cpp_includes.py
        language: python
        files: ^xls/.*\.(h|cc)$
        exclude: ^xls/contrib/
        types: [text]
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.4
    hooks:
      - id: pylint
        files: ^xls/dev_tools/check_.*.py$
        args: [
          --rcfile=.pylintrc
        ]
