// Copyright 2026 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Standalone C++20 compile test of a header generated by aot_compiler_main
// (--output_cpp_header). The header must be self-contained: this file does not
// link against XLS, protobuf, Abseil or LLVM, and only depends on the standard
// library.
//
// The header under test is produced by the genrule
// //xls/jit:aot_cpp_header_test_header for xls/jit/aot_cpp_header_test.ir.

#include <type_traits>

#include "xls/jit/aot_cpp_header_guard_lower_test_generated.h"
#include "xls/jit/aot_cpp_header_guard_upper_test_generated.h"
#include "xls/jit/aot_cpp_header_test_generated.h"
#include "xls/jit/aot_cpp_header_zero_arg_test_generated.h"

namespace generated = aot_cpp::generated::Step;

static_assert(aot_cpp::generated::ZeroArgStep::kInputCount == 0);
static_assert(
    aot_cpp::generated::ZeroArgStep::kPackedInputBitCounts.size() == 0);
// Both declarations exist: case-only differences no longer collide through
// uppercased include guards.
static_assert(guard_test::generated::Step::kInputCount == 2);
static_assert(GUARD_TEST::GENERATED::STEP::kInputCount == 2);

static_assert(generated::kInputCount == 2);
static_assert(generated::kOutputCount == 1);
static_assert(generated::kPackedInputBitCounts[0] == 8);  // bits[3] -> 1 byte.
static_assert(generated::kPackedInputBitCounts[1] == 16);  // bits[8][2] -> 2 bytes.
static_assert(generated::kPackedOutputBitCounts[0] == 8);  // tuple -> 1 byte.

static_assert(generated::Input0::kBitCount == 3);
static_assert(std::is_same_v<generated::Input0, generated::X>);
static_assert(std::is_same_v<generated::Input1, generated::Arr>);
static_assert(generated::Input1::kBitCount == 16);
static_assert(
    std::is_same_v<generated::Input1::Element, generated::Bits<8>>);

static_assert(generated::Result::kBitCount == 8);
static_assert(generated::Result::kSize == 2);
static_assert(
    std::is_same_v<generated::Result::Element<0>, generated::Bits<1>>);
static_assert(
    std::is_same_v<generated::Result::Element<1>, generated::Bits<7>>);

// XLS packed tuples are MSB-to-LSB: element zero is the highest element, its
// offset from the least significant bit equals the sum of the trailing
// element bit counts.
static_assert(generated::Result::Offset<0>() == 7);
static_assert(generated::Result::Offset<1>() == 0);
// Nested tuple offsets.
using NestedTuple =
    generated::Tuple<generated::Tuple<generated::Bits<3>, generated::Bits<5>>,
                     generated::Bits<4>>;
static_assert(NestedTuple::kBitCount == 12);
static_assert(NestedTuple::Offset<0>() == 4);
static_assert(NestedTuple::Offset<1>() == 0);
static_assert(NestedTuple::Element<0>::Offset<0>() == 5);
static_assert(NestedTuple::Element<0>::Offset<1>() == 0);

// The support templates agree with the metadata bit counts.
static_assert(generated::PackedBitCount<generated::Input0::kBitCount> ==
              generated::kPackedInputBitCounts[0]);
static_assert(generated::PackedBitCount<generated::Result::kBitCount> ==
              generated::kPackedOutputBitCounts[0]);

// The stable identifier trampoline to the real packed symbol.
static_assert(generated::kPackedFunction == &generated::StepInvokePacked);
static_assert(
    std::is_same_v<generated::PackedFunction,
                   std::remove_cv_t<decltype(generated::kPackedFunction)>>);

int main() { return 0; }
