#
# Copyright 2026 The XLS Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Tests for the --output_cpp_header functionality of aot_compiler_main."""

import pathlib
import subprocess

from absl.testing import absltest
from xls.common import runfiles

_AOT_COMPILER = "xls/jit/aot_compiler_main"

_IR = """\
package aot_cpp_header_test

top fn aot_cpp_header_step(x: bits[3], arr: bits[8][2]) -> (bits[1], bits[7]) {
  bit_slice.1: bits[1] = bit_slice(x, start=2, width=1, id=1)
  literal.5: bits[32] = literal(value=0, id=5)
  array_index.2: bits[8] = array_index(arr, indices=[literal.5], id=2)
  bit_slice.3: bits[7] = bit_slice(array_index.2, start=0, width=7, id=3)
  ret tuple.4: (bits[1], bits[7]) = tuple(bit_slice.1, bit_slice.3, id=4)
}
"""


class AotCppHeaderCliTest(absltest.TestCase):

  def _write_ir(self):
    return self.create_tempfile(content=_IR).full_path

  def _header_args(self):
    return [
        "--cpp_namespace=aot_cpp::generated",
        "--cpp_entrypoint_name=Step",
    ]

  def _run(self, *args):
    return subprocess.run(
        [runfiles.get_path(_AOT_COMPILER), *args],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        encoding="utf-8",
    )

  def test_header_only_invocation(self):
    ir = self._write_ir()
    header = self.create_tempfile("generated.h").full_path
    proc = self._run("--input", ir, "--output_cpp_header", header,
                     *self._header_args())
    self.assertEqual(proc.returncode, 0, proc.stderr)
    contents = open(header).read()
    self.assertIn("Generated by XLS aot_compiler_main; do not edit.", contents)
    self.assertIn("namespace aot_cpp {", contents)
    self.assertIn("namespace Step {", contents)
    self.assertIn("using Input0 = Bits<3>;", contents)
    self.assertIn("using Input1 = Array<Bits<8>, 2>;", contents)
    self.assertIn("using Result = Tuple<Bits<1>, Bits<7>>;", contents)
    self.assertIn("kPackedInputBitCounts = {8, 16}", contents)
    self.assertIn("asm(\"aot_cpp_header_step_packed\")",
                  contents)

  def test_header_requires_cpp_namespace(self):
    ir = self._write_ir()
    proc = self._run("--input", ir, "--output_cpp_header", "x.h",
                     "--cpp_entrypoint_name=Step")
    self.assertEqual(proc.returncode, 1)
    self.assertIn("cpp_namespace is required", proc.stdout)

  def test_header_requires_cpp_entrypoint_name(self):
    ir = self._write_ir()
    proc = self._run("--input", ir, "--output_cpp_header", "x.h",
                     "--cpp_namespace=aot_cpp::generated")
    self.assertEqual(proc.returncode, 1)
    self.assertIn("cpp_entrypoint_name is required", proc.stdout)

  def test_header_rejects_invalid_entrypoint_name(self):
    ir = self._write_ir()
    proc = self._run("--input", ir, "--output_cpp_header", "x.h",
                     "--cpp_namespace=aot_cpp::generated",
                     "--cpp_entrypoint_name=not valid")
    self.assertEqual(proc.returncode, 1)
    self.assertIn("not a valid C++ identifier", proc.stdout)

  def test_cpp_options_require_header_output(self):
    ir = self._write_ir()
    proc = self._run("--input", ir, "--cpp_entrypoint_name=Step")
    self.assertEqual(proc.returncode, 1)
    self.assertIn("may only be used with --output_cpp_header", proc.stdout)

  def test_invalid_header_does_not_partially_write_metadata(self):
    ir = self._write_ir()
    tmpdir = pathlib.Path(self.create_tempdir().full_path)
    proto = tmpdir / "test.pb"
    header = tmpdir / "test.h"
    obj = tmpdir / "test.o"
    obj.write_bytes(b"existing object")
    proc = self._run(
        "--input", ir, "--output_object", str(obj),
        "--output_proto", str(proto),
        "--output_cpp_header", str(header),
        "--cpp_namespace=aot_cpp::generated",
        "--cpp_entrypoint_name=not valid")
    self.assertEqual(proc.returncode, 1)
    self.assertEqual(obj.read_bytes(), b"existing object")
    self.assertFalse(proto.exists())
    self.assertFalse(header.exists())

  def test_object_proto_and_header_in_one_invocation(self):
    ir = self._write_ir()
    tmpdir = pathlib.Path(self.create_tempdir().full_path)
    obj = tmpdir / "test.o"
    proto = tmpdir / "test.pb"
    header = tmpdir / "test.h"
    proc = self._run(
        "--input", ir, "--top", "aot_cpp_header_step", "--top_type", "FUNCTION",
        "--output_object", str(obj), "--output_proto", str(proto),
        "--output_cpp_header", str(header), *self._header_args())
    self.assertEqual(proc.returncode, 0, proc.stderr)
    self.assertTrue(obj.exists())
    self.assertTrue(proto.exists())
    self.assertTrue(header.exists())
    contents = open(header).read()
    # Result tuple (bits[1], bits[7]) has only 8 bits but header must describe
    # the true structural result type.
    self.assertIn("using Result = Tuple<Bits<1>, Bits<7>>;", contents)


if __name__ == "__main__":
  absltest.main()
