// Copyright 2025 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_CODEGEN_VAST_DSLX_TYPE_FIXER_H_
#define XLS_CODEGEN_VAST_DSLX_TYPE_FIXER_H_

#include <memory>

#include "xls/dslx/frontend/ast_cloner.h"
#include "xls/dslx/type_system/type_info.h"

namespace xls {

// A utility used internally by a `DslxBuilder` to perform final cleanup on an
// AST generated by VAST->DSLX translation. The builder performs a preliminary
// run of DSLX type inference on a "draft" of its generated DSLX. It then
// provides the resulting `TypeInfo` to the fixer, which uses the info to make
// decisions.
class DslxTypeFixer {
 public:
  virtual ~DslxTypeFixer() = default;

  // Deals out a `CloneReplacer` that can be used to transform the draft AST
  // into a fixed AST.
  virtual dslx::CloneReplacer GetReplacer(const dslx::TypeInfo* ti) = 0;
};

// Deals out a type fixer.
std::unique_ptr<DslxTypeFixer> CreateDslxTypeFixer();

}  // namespace xls

#endif  // XLS_CODEGEN_VAST_DSLX_TYPE_FIXER_H_
