// Copyright 2026 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "xls/experimental/busperf/busperf_yaml_generator.h"

#include <string>
#include <string_view>
#include <vector>

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/container/flat_hash_map.h"
#include "absl/log/check.h"
#include "absl/status/status.h"
#include "google/protobuf/text_format.h"
#include "xls/codegen/module_signature.pb.h"
#include "xls/common/status/matchers.h"

namespace xls::busperf {
namespace {

using ::absl_testing::IsOkAndHolds;
using ::absl_testing::StatusIs;
using ::testing::HasSubstr;

verilog::ModuleSignatureProto ParseSignature(std::string_view text) {
  verilog::ModuleSignatureProto proto;
  CHECK(google::protobuf::TextFormat::ParseFromString(std::string(text),
                                                       &proto));
  return proto;
}

constexpr std::string_view kPassthroughSignature = R"pb(
  module_name: "passthrough"
  clock_name: "clk"
  reset { name: "rst" active_low: false }
  channel_interfaces {
    channel_name: "_data_r"
    direction: CHANNEL_DIRECTION_RECEIVE
    kind: CHANNEL_KIND_STREAMING
    streaming {
      flow_control: CHANNEL_FLOW_CONTROL_READY_VALID
      data_port_name: "_data_r"
      ready_port_name: "_data_r_rdy"
      valid_port_name: "_data_r_vld"
    }
  }
  channel_interfaces {
    channel_name: "_data_s"
    direction: CHANNEL_DIRECTION_SEND
    kind: CHANNEL_KIND_STREAMING
    streaming {
      flow_control: CHANNEL_FLOW_CONTROL_READY_VALID
      data_port_name: "_data_s"
      ready_port_name: "_data_s_rdy"
      valid_port_name: "_data_s_vld"
    }
  }
)pb";

TEST(BusperfYamlGeneratorTest, FlatDesignEmitsBothChannels) {
  verilog::ModuleSignatureProto signature =
      ParseSignature(kPassthroughSignature);
  std::vector<std::string> scope = {"tb_passthrough", "dut"};

  EXPECT_THAT(
      GenerateBusperfYaml(signature, scope, /*child_signatures=*/{}),
      IsOkAndHolds(
          "# Auto-generated by xls_sig_to_busperf from an XLS\n"
          "# ModuleSignatureProto for module \"passthrough\".\n"
          "common_clk_rst_ifs:\n"
          "  main_clk: &main_clk\n"
          "    clock: \"clk\"\n"
          "    reset: \"rst\"\n"
          "    reset_type: \"high\"\n"
          "\n"
          "interfaces:\n"
          "  \"_data_r\":\n"
          "    scope: [\"tb_passthrough\", \"dut\"]\n"
          "    clk_rst_if: *main_clk\n"
          "\n"
          "    handshake: \"ReadyValid\"\n"
          "    ready: \"_data_r_rdy\"\n"
          "    valid: \"_data_r_vld\"\n"
          "\n"
          "  \"_data_s\":\n"
          "    scope: [\"tb_passthrough\", \"dut\"]\n"
          "    clk_rst_if: *main_clk\n"
          "\n"
          "    handshake: \"ReadyValid\"\n"
          "    ready: \"_data_s_rdy\"\n"
          "    valid: \"_data_s_vld\"\n"));
}

TEST(BusperfYamlGeneratorTest, SkipsNonReadyValidChannels) {
  verilog::ModuleSignatureProto signature = ParseSignature(R"pb(
    module_name: "single_val"
    clock_name: "clk"
    reset { name: "rst" }
    channel_interfaces {
      channel_name: "config"
      direction: CHANNEL_DIRECTION_RECEIVE
      kind: CHANNEL_KIND_SINGLE_VALUE
      single_value { data_port_name: "config" }
    }
    channel_interfaces {
      channel_name: "_data"
      direction: CHANNEL_DIRECTION_RECEIVE
      kind: CHANNEL_KIND_STREAMING
      streaming {
        flow_control: CHANNEL_FLOW_CONTROL_READY_VALID
        data_port_name: "_data"
        ready_port_name: "_data_rdy"
        valid_port_name: "_data_vld"
      }
    }
  )pb");

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string yaml,
      GenerateBusperfYaml(signature, {"dut"}, /*child_signatures=*/{}));
  EXPECT_THAT(yaml, testing::Not(HasSubstr("config")));
  EXPECT_THAT(yaml, HasSubstr("\"_data\":"));
}

TEST(BusperfYamlGeneratorTest, HierarchicalDesignRecursesIntoChildren) {
  verilog::ModuleSignatureProto parent = ParseSignature(R"pb(
    module_name: "hier_top"
    clock_name: "clk"
    reset { name: "rst" }
    instantiations {
      block_instantiation {
        block_name: "__hier__Doubler_0_next"
        instance_name: "__hier__Doubler_0_next_inst"
      }
    }
  )pb");
  verilog::ModuleSignatureProto child = ParseSignature(R"pb(
    module_name: "__hier__Doubler_0_next"
    channel_interfaces {
      channel_name: "_in_ch"
      direction: CHANNEL_DIRECTION_RECEIVE
      kind: CHANNEL_KIND_STREAMING
      streaming {
        flow_control: CHANNEL_FLOW_CONTROL_READY_VALID
        data_port_name: "_in_ch"
        ready_port_name: "_in_ch_rdy"
        valid_port_name: "_in_ch_vld"
      }
    }
  )pb");
  absl::flat_hash_map<std::string, verilog::ModuleSignatureProto>
      child_signatures = {{"__hier__Doubler_0_next", child}};

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string yaml,
      GenerateBusperfYaml(parent, {"tb_hier", "dut"}, child_signatures));
  EXPECT_THAT(yaml, HasSubstr("\"__hier__Doubler_0_next_inst._in_ch\":"));
  EXPECT_THAT(yaml, HasSubstr("scope: [\"tb_hier\", \"dut\", "
                              "\"__hier__Doubler_0_next_inst\"]"));
  EXPECT_THAT(yaml, HasSubstr("ready: \"_in_ch_rdy\""));
}

TEST(BusperfYamlGeneratorTest, GrandchildRecursionAccumulatesScopeAndName) {
  // top -> mid_inst -> leaf_inst: recursion beyond one hierarchy level.
  verilog::ModuleSignatureProto top = ParseSignature(R"pb(
    module_name: "top"
    clock_name: "clk"
    reset { name: "rst" }
    instantiations {
      block_instantiation { block_name: "mid" instance_name: "mid_inst" }
    }
  )pb");
  verilog::ModuleSignatureProto mid = ParseSignature(R"pb(
    module_name: "mid"
    instantiations {
      block_instantiation { block_name: "leaf" instance_name: "leaf_inst" }
    }
  )pb");
  verilog::ModuleSignatureProto leaf = ParseSignature(R"pb(
    module_name: "leaf"
    channel_interfaces {
      channel_name: "_data"
      direction: CHANNEL_DIRECTION_SEND
      kind: CHANNEL_KIND_STREAMING
      streaming {
        flow_control: CHANNEL_FLOW_CONTROL_READY_VALID
        data_port_name: "_data"
        ready_port_name: "_data_rdy"
        valid_port_name: "_data_vld"
      }
    }
  )pb");
  absl::flat_hash_map<std::string, verilog::ModuleSignatureProto>
      child_signatures = {{"mid", mid}, {"leaf", leaf}};

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string yaml,
      GenerateBusperfYaml(top, {"tb_top", "dut"}, child_signatures));
  EXPECT_THAT(yaml, HasSubstr("\"mid_inst.leaf_inst._data\":"));
  EXPECT_THAT(yaml, HasSubstr("scope: [\"tb_top\", \"dut\", \"mid_inst\", "
                              "\"leaf_inst\"]"));
  EXPECT_THAT(yaml, HasSubstr("valid: \"_data_vld\""));
}

TEST(BusperfYamlGeneratorTest, MissingChildSignatureIsSkippedNotFatal) {
  // Unresolved instantiation is skipped; the top's own channel still emits.
  verilog::ModuleSignatureProto parent = ParseSignature(R"pb(
    module_name: "hier_top"
    clock_name: "clk"
    reset { name: "rst" }
    channel_interfaces {
      channel_name: "_data"
      direction: CHANNEL_DIRECTION_RECEIVE
      kind: CHANNEL_KIND_STREAMING
      streaming {
        flow_control: CHANNEL_FLOW_CONTROL_READY_VALID
        data_port_name: "_data"
        ready_port_name: "_data_rdy"
        valid_port_name: "_data_vld"
      }
    }
    instantiations {
      block_instantiation {
        block_name: "unresolved_block"
        instance_name: "unresolved_inst"
      }
    }
  )pb");

  XLS_ASSERT_OK_AND_ASSIGN(
      std::string yaml,
      GenerateBusperfYaml(parent, {"dut"}, /*child_signatures=*/{}));
  EXPECT_THAT(yaml, HasSubstr("\"_data\":"));
  EXPECT_THAT(yaml, testing::Not(HasSubstr("unresolved_inst")));
}

TEST(BusperfYamlGeneratorTest, NoReadyValidChannelsIsAnError) {
  verilog::ModuleSignatureProto signature = ParseSignature(R"pb(
    module_name: "no_channels"
    clock_name: "clk"
    reset { name: "rst" }
  )pb");

  EXPECT_THAT(
      GenerateBusperfYaml(signature, {"dut"}, /*child_signatures=*/{}),
      StatusIs(absl::StatusCode::kInvalidArgument,
               HasSubstr("CHANNEL_FLOW_CONTROL_READY_VALID "
                         "channel_interfaces found")));
}

}  // namespace
}  // namespace xls::busperf
