# Copyright 2026 The XLS Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This module contains the DSLX-related test build rules for XLS."""

load("@bazel_skylib//lib:dicts.bzl", "dicts")
load(
    "//xls/build_rules:xls_common_rules.bzl",
    "append_cmd_line_args_to",
    "append_default_to_args",
    "args_to_string",
    "get_runfiles_for_xls",
    "get_transitive_built_files_for_xls",
    "is_args_valid",
)
load("//xls/build_rules:xls_dslx_common.bzl", "get_src_files_from_dslx_library_as_input", "xls_dslx_library_as_input_attrs")
load(
    "//xls/build_rules:xls_toolchains.bzl",
    "xls_toolchain_attrs",
)

visibility(["//xls/build_rules/..."])

_DEFAULT_DSLX_TEST_ARGS = {
    "compare": "none",
}

# Common attributes for DSLX testing.
xls_dslx_test_common_attrs = {
    "configured_values": attr.string_dict(
        doc = "Dictionary of overrides to use for overridable constants " +
              "in DSLX processing. Format is \"key\":\"value\" pairs.",
    ),
    "dslx_test_args": attr.string_dict(
        doc = "Arguments of the DSLX interpreter executable. For details " +
              "on the arguments, refer to the interpreter_main " +
              "application at " +
              "//xls/dslx/interpreter_main.cc.",
    ),
    "evaluator": attr.string(
        default = "dslx-interpreter",
        values = ["dslx-interpreter", "ir-jit", "ir-interpreter"],
        doc = "What type of evaluator to use. 'ir-jit' will execute the tests faster " +
              "but has higher startup time and less helpful failure messages. Options: " +
              '["dslx-interpreter" (default), "ir-jit", "ir-interpreter"]. Note: The ' +
              "'compare' dslx_test_arg is only available with the default 'dslx-interpreter' " +
              "evaluator.",
    ),
}

def get_dslx_test_cmd(ctx, src_files_to_test):
    """Returns the runfiles and commands to execute the sources files.

    Args:
      ctx: The current rule's context object.
      src_files_to_test: A list of source files to test.

    Returns:
      A tuple with the following elements in the order presented:
        1. The runfiles to execute the commands.
        1. A list of commands.
    """

    # Get runfiles.
    dslx_interpreter_tool_runfiles = (
        ctx.attr._xls_dslx_interpreter_tool[DefaultInfo].default_runfiles
    )
    runfiles = get_runfiles_for_xls(
        ctx,
        [dslx_interpreter_tool_runfiles],
        src_files_to_test,
    )

    cmds = []
    for src in src_files_to_test:
        cmds.append(_get_dslx_test_cmdline(ctx, src, src_files_to_test))
    return runfiles, cmds

def _get_dslx_test_cmdline(ctx, src, all_srcs, append_cmd_line_args = True):
    """Returns the command that executes in the xls_dslx_test rule.

    Args:
      ctx: The current rule's context object.
      src: The file to test.
      all_srcs: All dslx sources, including dependencies as part of the test.
      append_cmd_line_args: Flag controlling appending the command-line
        arguments invoking the command generated by this function. When set to
        True, the command-line arguments invoking the command are appended.
        Otherwise, the command-line arguments are not appended.

    Returns:
      The command that executes in the xls_dslx_test rule.
    """
    dslx_interpreter_tool = ctx.file._xls_dslx_interpreter_tool
    _dslx_test_args = append_default_to_args(
        ctx.attr.dslx_test_args,
        _DEFAULT_DSLX_TEST_ARGS,
    )

    DSLX_TEST_FLAGS = (
        "compare",
        "dslx_path",
        "warnings_as_errors",
        "disable_warnings",
        "enable_warnings",
        "max_ticks",
        "format_preference",
        "configured_values",
        "lower_to_proc_scoped_channels",
        "lower_to_ir",
        "convert_tests",
        "simulate_bounded_fifos",
    )

    dslx_test_args = dict(_dslx_test_args)

    # With runs outside a monorepo, the execution root for the workspace of
    # the binary can be different with the execroot, requiring to change
    # the dslx stdlib search path accordingly.
    # e.g., Label("@repo//pkg/xls:binary").workspace_root == "external/repo"
    wsroot = ctx.attr._xls_dslx_interpreter_tool.label.workspace_root
    wsroot_dslx_path = ":{}".format(wsroot) if wsroot != "" else ""
    dslx_srcs_wsroot = ":".join([s.owner.workspace_root for s in all_srcs] +
                                [ctx.genfiles_dir.path + "/" + s.owner.workspace_root for s in all_srcs])
    dslx_srcs_wsroot_path = ":{}".format(dslx_srcs_wsroot) if dslx_srcs_wsroot != "" else ""

    dslx_test_args["dslx_path"] = (
        dslx_test_args.get("dslx_path", "") + ":${PWD}:" +
        ctx.genfiles_dir.path + ":" + ctx.bin_dir.path +
        dslx_srcs_wsroot_path + wsroot_dslx_path
    )
    if ctx.attr.configured_values:
        formatted_values = []
        for k, v in ctx.attr.configured_values.items():
            formatted_values.append("{}:{}".format(k, v))
        dslx_test_args["configured_values"] = ",".join(formatted_values)
    is_args_valid(dslx_test_args, DSLX_TEST_FLAGS)
    dslx_test_args["evaluator"] = ctx.attr.evaluator
    my_args = args_to_string(dslx_test_args)

    cmd = "{} {} {}".format(
        dslx_interpreter_tool.short_path,
        src.short_path,
        my_args,
    )

    # Append command-line arguments.
    if append_cmd_line_args:
        cmd = append_cmd_line_args_to(cmd)

    return cmd

def _xls_dslx_test_impl(ctx):
    """The implementation of the 'xls_dslx_test' rule.

    Executes the tests and quick checks of a DSLX source file.

    Args:
      ctx: The current rule's context object.

    Returns:
      DefaultInfo provider
    """
    src_files_to_test = get_src_files_from_dslx_library_as_input(ctx)

    runfiles, cmds = get_dslx_test_cmd(ctx, src_files_to_test)

    executable_file = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        output = executable_file,
        content = "\n".join([
            "#!/usr/bin/env bash",
            "set -e",
            "\n".join(cmds),
            "exit 0",
        ]),
        is_executable = True,
    )
    return [
        DefaultInfo(
            runfiles = runfiles,
            files = depset(
                direct = [executable_file],
                transitive = get_transitive_built_files_for_xls(ctx),
            ),
            executable = executable_file,
        ),
    ]

xls_dslx_test = rule(
    implementation = _xls_dslx_test_impl,
    attrs = dicts.add(
        xls_dslx_library_as_input_attrs,
        xls_dslx_test_common_attrs,
        dicts.pick(xls_toolchain_attrs, ["_xls_dslx_interpreter_tool"]),
    ),
    test = True,
)
