// Copyright 2020 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_BDD_SIMPLIFICATION_PASS_H_
#define XLS_PASSES_BDD_SIMPLIFICATION_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/function_base.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Runs BDD-based simplifications on the function.
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// The `BddSimplificationPass` leverages Binary Decision Diagrams (BDDs) to
// perform advanced logical simplifications on the IR. BDDs provide a canonical
// representation of Boolean functions, enabling powerful, logic-level
// optimizations that are challenging for traditional syntactic or
// dataflow-based passes.
//
// The pass currently focuses on the following key areas:
//
// 1.  **Replacement of Statically Known Values with Literals**: Through BDD
//     analysis, if a node's value (or specific bits of it) can be determined
//     to be constant under all reachable conditions, it is replaced with a
//     literal.
//
//     Example: If `my_and: bits[1] = and(param_x, param_y)` and BDD analysis
//     proves `param_x` is always `0b0`, then `my_and` can be replaced with
//     `literal(0, bits=1)`.
//
// 2.  **Removal of Redundant Operands in Boolean Operations**: For N-ary
//     Boolean operations (`and`, `nand`, `or`, `nor`), the pass identifies and
//     removes operands that are logically redundant given the values or
//     relationships of other operands. For instance, in `and(A, B, C)`, if `C`
//     is always true whenever `A` and `B` are true, `C` is redundant.
//
//     Example: If `C` is a predicate `a_and_b: bits[1] = and(A, B)`
//
//     ret my_and: bits[1] = and(A, B, C)
//
//     This can be simplified to:
//
//     ret my_and: bits[1] = and(A, B)
//
//
// 3.  **Collapse of Select Chains into OneHotSelects** (at `opt_level >= 2`):
//     Chains of binary `select` operations, particularly where one case of a
//     `select` feeds into another `select` (e.g.,
//     `sel(pred_a, {val_a, sel(pred_b, {val_b, default_val})})`), are
//     transformed into a single `one_hot_select` if the selectors are provably
//     disjoint (at most one can be true at any given time). This simplifies the
//     IR structure and can lead to more efficient hardware implementations.
//
// 4.  **Replacement of Two-Way OneHotSelect with Select** (at `opt_level >=
//     2`):
//     A `one_hot_select` with a 2-bit selector that is known to be one-hot can
//     be replaced with a simpler `select` operation, as the one-hot property
//     means the decision effectively depends on a single bit. This reduces the
//     complexity of the select operation.
//
// 5.  **Simplification of PrioritySelect Operations** (at `opt_level >= 1`):
//     If BDD analysis determines that the selector of a `priority_select` is
//     guaranteed to have at least one bit set within a certain range, the
//     `priority_select` can be narrowed. This involves trimming higher-priority
//     cases that are guaranteed not to be selected, effectively reducing the
//     number of cases the hardware needs to evaluate.
//
// As BDD-based analysis can be computationally intensive, some optimizations
// are applied conditionally based on the optimization level (`opt_level`).
class BddSimplificationPass : public OptimizationFunctionBasePass {
 public:
  static constexpr std::string_view kName = "bdd_simp";
  explicit BddSimplificationPass()
      : OptimizationFunctionBasePass(kName, "BDD-based Simplification") {}
  ~BddSimplificationPass() override = default;

 protected:
  // Run all registered passes in order of registration.
  absl::StatusOr<bool> RunOnFunctionBaseInternal(
      FunctionBase* f, const OptimizationPassOptions& options,
      PassResults* results, OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_BDD_SIMPLIFICATION_PASS_H_
