// Copyright 2021 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_CONDITIONAL_SPECIALIZATION_PASS_H_
#define XLS_PASSES_CONDITIONAL_SPECIALIZATION_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/function_base.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Pass which specializes arms of select operations based on their selector
// value. When analyzing a particular arm of a `sel`, the value of the
// selector is known. This knowledge can be used to simplify the expression
// within the arm.
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// For example, consider the following IR:
//
// ```
// fn f(a: bits[1], b: bits[31], z: bits[32]) -> bits[32] {
//   concat: bits[32] = concat(a, b)
//   ret sel.2: bits[32] = sel(a, cases=[z, concat])
// }
// ```
//
//
// In the `sel` operation, the selector is `a`. When considering `case[1]` (the
// `concat` operation), we know that `a` must have the value `1`. Therefore, the
// `concat(a, b)` can be simplified to `concat(1, b)`. The pass will transform
// the `sel` to:
//
//
// ```
// sel.2: bits[32] = sel(a, cases=[z, concat(literal(1), b)])
// ```
//
//
// This optimization applies to `sel`, `priority_sel`, and `one_hot_sel`. It can
// also use Binary Decision Diagrams (BDDs) for more powerful analysis of the
// conditions.
class ConditionalSpecializationPass : public OptimizationFunctionBasePass {
 public:
  static constexpr std::string_view kName = "cond_spec";
  // If `use_bdd` is true, then binary decision diagrams (BDDs) are used for
  // stronger analysis at the cost of slower transformation.
  explicit ConditionalSpecializationPass(bool use_bdd)
      : OptimizationFunctionBasePass(ConfiguredName(use_bdd),
                                     "Conditional specialization"),
        use_bdd_(use_bdd) {}
  ~ConditionalSpecializationPass() override = default;

 protected:
  bool use_bdd_;
  absl::StatusOr<bool> RunOnFunctionBaseInternal(
      FunctionBase* f, const OptimizationPassOptions& options,
      PassResults* results, OptimizationContext& context) const override;

 private:
  static std::string_view ConfiguredName(bool use_bdd) {
    if (use_bdd) {
      return "cond_spec(Bdd)";
    }
    return "cond_spec(noBdd)";
  }
};

}  // namespace xls

#endif  // XLS_PASSES_CONDITIONAL_SPECIALIZATION_PASS_H_
