// Copyright 2020 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_CSE_PASS_H_
#define XLS_PASSES_CSE_PASS_H_

#include <string_view>

#include "absl/container/flat_hash_map.h"
#include "absl/status/statusor.h"
#include "xls/ir/function_base.h"
#include "xls/ir/node.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// This function is called by the `CsePass` to merge together common
// subexpressions. It exists so that you can call it inside other passes and
// extract which nodes were merged. Each replacement done by the pass is added
// to the `replacements` hash map if it is not `nullptr`. Note that for many
// common uses of the `replacements` map, you'll want to compute the transitive
// closure of the relation rather than using it as-is.
absl::StatusOr<bool> RunCse(FunctionBase* f,
                            absl::flat_hash_map<Node*, Node*>* replacements,
                            bool common_literals = true);

// Computes the fixed point of a strict partial order, i.e.: the relation that
// solves the equation `F = R ∘ F` where `R` is the given strict partial order.
template <typename T>
absl::flat_hash_map<T, T> FixedPointOfSPO(
    const absl::flat_hash_map<T, T>& relation) {
  absl::flat_hash_map<T, T> result;
  for (const auto& [source, target] : relation) {
    T node = target;
    while (relation.contains(node)) {
      if (node == relation.at(node)) {
        break;
      }
      node = relation.at(node);
    }
    result[source] = node;
  }
  return result;
}

// Pass which performs common subexpression elimination. Equivalent ops with the
// same operands are commoned. The pass can find arbitrarily large common
// expressions.
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// The `CsePass` (Common Subexpression Elimination) is an optimization pass in
// XLS that identifies and merges equivalent computations within a function or
// proc. The primary goal is to eliminate redundant calculations, thereby
// reducing the size of the generated hardware, improving performance, and
// making the IR more compact.
//
// The pass operates by building a canonical representation (`CseNode`) for each
// operation in the IR. Two operations are considered equivalent if they have:
//
// *   The same opcode (`Op`).
// *   The same operand list (with a canonical ordering applied for commutative
//     operations like `add` or `and`).
// *   The same additional configuration data (e.g., `start` and `width` for
//     `bit_slice`, `index` for `tuple_index`).
// *   The same result type (`Type`).
//
// Here's a breakdown of how the pass works:
//
// 1.  **`CseNode` Representation**: A `CseNode` object is created for each
//     `Node` in the IR. This `CseNode` captures the essential characteristics
//     that define equivalence, including the opcode, a sorted list of its
//     operands (canonicalized for commutative operations), any non-operand
//     configuration data, and the result type. For side-effecting operations
//     (other than `gate`) and certain control-flow-related operations
//     (`param`, `next`, `receive`, `send`, `assert`, `cover`, etc.), a unique
//     identifier is assigned to prevent them from being considered equivalent,
//     even if their underlying data appears identical.
//
// 2.  **`CseNodeArena`**: A `CseNodeArena` manages the creation and storage of
//     `CseNode` objects. It ensures that only one `CseNode` instance exists for
//     each unique canonical operation. When a `Node` is processed, the arena
//     either returns an existing `CseNode` (if an equivalent one has already
//     been seen) or creates a new one.
//
// 3.  **Equivalence Grouping**: The pass traverses the IR in topological order.
//     For each `Node`, it obtains its `CseNode` representation. All `Node`s
//     that map to the same `CseNode` are grouped together into an "equivalence
//     bucket."
//
// 4.  **Replacement**: After all nodes have been processed and grouped:
//
//     *   For each equivalence bucket containing more than one `Node`, a
//         "representative" node is chosen from that bucket. The selection
//         criteria for the representative prioritize nodes with shorter
//         assigned names, and then by node ID for determinism.
//
//     *   All other `Node`s in the bucket (the "duplicates") are then replaced
//         by the representative node. This means all users of the duplicate
//         nodes are rewired to use the single representative node instead.
//
//     *   The pass can optionally common `literal` nodes. If `common_literals`
//         is `false`, each `literal` is treated as unique, preventing them from
//         being merged. This can be useful if preserving distinct literal nodes
//         is important for some later pass.
//
// 5.  **Post-DCE**: After `CsePass` runs, a `DeadCodeEliminationPass` is
//     typically executed. This is because replacing duplicate nodes with a
//     representative leaves the original duplicate nodes with no remaining
//     users, making them dead code that can then be safely removed from the IR.
//
// Example:
// Consider a function with two identical `and` operations, followed by
// identical `neg` and `or` operations:
//
//
// ```
// // Original IR snippet
// fn nontrivial(x: bits[8], y: bits[8], z: bits[8]) -> bits[8] {
//   and.1: bits[8] = and(x, y)
//   neg.2: bits[8] = neg(and.1)
//   or.3: bits[8] = or(neg.2, z)
//
//   and.4: bits[8] = and(x, y) // Identical to and.1
//   neg.5: bits[8] = neg(and.4) // Identical to neg.2
//   or.6: bits[8] = or(neg.5, z) // Identical to or.3
//
//   ret add.7: bits[8] = add(or.3, or.6)
// }
// ```
//
//
// The `CsePass` would identify that `and.1` and `and.4` are equivalent; `neg.2`
// and `neg.5` are equivalent; and `or.3` and `or.6` are equivalent. It would
// choose one of each pair as a representative and replace the duplicates.
// After a subsequent DCE pass, the IR would be simplified to:
//
//
// ```
// // Optimized IR (after CsePass and DCE)
// fn nontrivial(x: bits[8], y: bits[8], z: bits[8]) -> bits[8] {
//   and.1: bits[8] = and(x, y)
//   neg.2: bits[8] = neg(and.1)
//   or.3: bits[8] = or(neg.2, z)
//
//   ret add.7: bits[8] = add(or.3, or.3) // or.6 replaced by or.3
// }
// ```
//
// This effectively shares the computation of the redundant `and`, `neg`, and
// `or` operations, significantly reducing redundant logic and hardware
// requirements.
class CsePass : public OptimizationFunctionBasePass {
 public:
  static constexpr std::string_view kName = "cse";

  // If `common_literals` is true then literals are included in the
  // transformations, otherwise literals are not commoned.
  explicit CsePass(bool common_literals = true)
      : OptimizationFunctionBasePass(kName, "Common subexpression elimination"),
        common_literals_(common_literals) {}
  ~CsePass() override = default;

 protected:
  absl::StatusOr<bool> RunOnFunctionBaseInternal(
      FunctionBase* f, const OptimizationPassOptions& options,
      PassResults* results, OptimizationContext& context) const override;

  bool common_literals_;
};

}  // namespace xls

#endif  // XLS_PASSES_CSE_PASS_H_
