// Copyright 2024 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_DATAFLOW_SIMPLIFICATION_PASS_H_
#define XLS_PASSES_DATAFLOW_SIMPLIFICATION_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/function_base.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// An optimization which uses a lattice-based dataflow analysis to find
// equivalent nodes in the graph and replace them with a simpler form. The
// analysis traces through tuples, arrays, and select operations. Optimizations
// which can be performed by this pass:
//
//    tuple_index(tuple(x, y), index=1)  =>  y
//
//    select(selector, {z, z})  =>  z
//
//    array_index(array_update(A, x, index={42}), index={42})  =>  x
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// The `DataflowSimplificationPass` is an optimization pass in XLS that
// leverages a lattice-based dataflow analysis to identify and replace logically
// equivalent nodes in the Intermediate Representation (IR) with simpler, more
// direct forms. This pass is highly effective at "seeing through" structural
// operations such as tuples, arrays, and select statements to eliminate
// redundant computations and expose values that are directly available from
// their original source.
// The overarching goal is to reduce the overall complexity and size of the IR,
// leading to more compact and efficient hardware designs.
//
// **How it Works**:
//
// 1.  **`NodeSourceAnalysis`**: The core mechanism of this pass is the
//     `NodeSourceAnalysis` (implemented via `NodeSourceDataflowVisitor`). This
//     analysis precisely determines the "source" of every elemental component
//     (individual bits, tuple elements, array elements) within each node in the
//     IR graph. A "source" is defined as the original node or literal from
//     which a particular piece of data originates, tracing through
//     intermediate operations like `tuple_index`, `array_index`, `bit_slice`,
//     and `concat`. For example, if an operation is
//     `tuple_index(tuple(x, y), 1)`, the
//     effective source of this operation's output is directly `y`.
//
// 2.  **Equivalence Mapping (`source_map`)**: The pass performs a topological
//     sort of the function's nodes. During this traversal, it constructs a hash
//     map (`source_map`). The keys of this map are
//     `LeafTypeTreeView<NodeSource>` objects, which uniquely identify the
//     "source" of a node's data. The values are pointers to the `Node*` that
//     represents that canonical source.  If two distinct nodes are found to
//     have the same `LeafTypeTreeView<NodeSource>`, they are semantically
//     equivalent.
//
// 3.  **Simplification via Replacement**:
//     *   **Direct Replacement of Equivalent Nodes**: As the pass traverses the
//         graph in topological order, if the `NodeSource` of the current node
//         (`node`) is already present in the `source_map` (indicating that a
//         logically equivalent node (`it->second`) has already been processed),
//         then the current `node` is directly replaced by `it->second`. This
//         effectively eliminates redundant computations where the same value is
//         derived through different paths.
//
//         ```
//         // Original:
//         tuple.1: (bits[2], bits[42]) = tuple(x, y)
//         ret tuple_index.2: bits[42] = tuple_index(tuple.1, index=1)
//         // After optimization:
//         ret y: bits[42] = param(name=y) // tuple_index.2 replaced by y
//         ```
//
//     *   **Special Handling for Empty Types**: Nodes representing empty types
//         (e.g., zero-width bits, empty tuples) are handled with care. While
//         they are technically equivalent to each other, replacing them
//         indiscriminately can lead to infinite loops if, for example, two
//         parameters of empty types repeatedly replace each other's uses. To
//         prevent this, the pass explicitly skips replacing nodes of empty
//         types with other equivalent empty-type nodes.
//
// 4.  **`MaybeReplaceWithArrayOfExistingNodes` (Array Optimization)**:
//     This auxiliary function specifically targets `array` nodes. If an `array`
//     node is constructed entirely from elements that are themselves existing
//     nodes in the graph (and whose `NodeSource`s are already in the
//     `source_map`), the `array` node can be replaced by a more direct `array`
//     literal or a reference to an existing array operation. This is useful
//     for:
//     *   **Unboxing Arrays**: Simplifying `array_index(array(x), index=0)` to
//         just `x`.
//
//     *   **Reconstructing Arrays from Updates**: If a series of `array_update`
//         operations effectively reconstructs an array from individual elements
//         (some of which might be initial values), and the pass can track these
//         sources, it can replace the `array_update` chain with a direct
//         `array` operation.
//
//     *   **Eliminating Redundant Array Construction**: If an `array` is
//         constructed whose elements are simply `array_index` operations from
//         another existing array, the entire `array` construction can be
//         replaced by the original array.
//
//         ```
//         // Original:
//         element_0: bits[32] = array_index(a, indices=[zero])
//         element_1: bits[32] = array_index(a, indices=[one])
//         element_2: bits[32] = array_index(a, indices=[two])
//         ret array: bits[32][3] = array(element_0, element_1, element_2)
//         // After optimization:
//         ret a: bits[32][3] = param(name=a) // Replaced by original array 'a'
//         ```
//
//
// **Benefits**:
//
// *   **Semantic CSE**: Performs a powerful form of common subexpression
//     elimination that identifies logically equivalent computations even if
//     their IR structures are syntactically different.
//
// *   **IR Simplification**: Reduces the number of nodes in the IR by
//     eliminating redundant computations and simplifying dataflow paths through
//     aggregate types (tuples and arrays).
//
// *   **Hardware Efficiency**: Leads directly to more compact and efficient
//     hardware by removing redundant logic and simplifying complex data
//     structures, which translates to better area and performance metrics.
class DataflowSimplificationPass : public OptimizationFunctionBasePass {
 public:
  static constexpr std::string_view kName = "dataflow";
  explicit DataflowSimplificationPass()
      : OptimizationFunctionBasePass(kName, "Dataflow Optimization") {}
  ~DataflowSimplificationPass() override = default;

 protected:
  absl::StatusOr<bool> RunOnFunctionBaseInternal(
      FunctionBase* f, const OptimizationPassOptions& options,
      PassResults* results, OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_DATAFLOW_SIMPLIFICATION_PASS_H_
