// Copyright 2020 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Identity Removal - eliminate all identity() expressions.

#ifndef XLS_PASSES_IDENTITY_REMOVAL_PASS_H_
#define XLS_PASSES_IDENTITY_REMOVAL_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/function_base.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Identity Removal - eliminate all identity() expressions.
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// The `IdentityRemovalPass` is an optimization pass in XLS that focuses on
// simplifying the Intermediate Representation (IR) by eliminating all
// `identity()` expressions. An `identity()` operation simply passes its single
// operand through unchanged. While syntactically valid, these operations
// introduce unnecessary nodes into the graph, increasing its complexity without
// contributing any new computational value.
//
// **How it Works**:
//
// 1.  **Traversal**: The pass performs a forward traversal through all nodes in
//     the function or proc.
//
// 2.  **Identification**: For each node encountered, it checks if the node's
//     opcode (`op()`) is `Op::kIdentity`.
//
// 3.  **Replacement**: If an `identity()` node is found, all its uses are
//     directly replaced with its single operand. This means any node that was
//     consuming the output of the `identity()` operation will now directly
//     consume the input to the `identity()` operation.
//
// 4.  **Removal (Implicitly by DCE)**: After all uses of an `identity()` node
//     have been replaced, that `identity()` node itself becomes dead code (it
//     no longer has any consumers). A subsequent `DeadCodeEliminationPass` is
//     typically run after `IdentityRemovalPass` to remove these now-unused
//     `identity()` nodes, further cleaning up the IR.
//
// **Benefits**:
//
// *   **IR Simplification**: Directly reduces the number of nodes in the IR,
//     making the graph simpler and easier for subsequent passes to analyze and
//     transform.
//
// *   **Hardware Reduction**: Eliminates unnecessary wires and buffers that
//     might otherwise be generated for `identity()` operations in hardware,
//     contributing to smaller area.
//
// *   **Improved Performance**: Removing redundant operations can slightly
//     improve simulation and synthesis performance by reducing the total amount
//     of logic.
//
// Example:
// Consider a function with a chain of `identity()` operations that pass through
// intermediate results:
//
//
// ```
// // Original IR snippet
// fn simple_neg(x: bits[8]) -> bits[8] {
//   one: bits[8] = literal(value=1)
//   v1:  bits[8] = identity(x)
//   add: bits[8] = add(v1, one)
//   v2:  bits[8] = identity(add)
//   v3:  bits[8] = identity(v2)
//   ret add2:bits[8] = sub(v3, one)
// }
// ```
//
//
// The `IdentityRemovalPass` would process `v1`, `v2`, and `v3`, replacing their
// uses with their respective operands. After this pass and a subsequent
// `DeadCodeEliminationPass`, the IR would be simplified to:
//
//
// ```
// // Optimized IR (after IdentityRemovalPass and DCE)
// fn simple_neg(x: bits[8]) -> bits[8] {
//   one: bits[8] = literal(value=1)
//   add: bits[8] = add(x, one)          // v1 replaced by x
//   // v3 replaced by add (which was v2's replacement)
//   ret add2:bits[8] = sub(add, one)
// }
// ```
//
// This effectively removes all the intermediate `identity()` nodes,
// streamlining the dataflow and simplifying the overall design.
class IdentityRemovalPass : public OptimizationFunctionBasePass {
 public:
  static constexpr std::string_view kName = "ident_remove";
  IdentityRemovalPass()
      : OptimizationFunctionBasePass(kName, "Identity Removal") {}
  ~IdentityRemovalPass() override = default;

 protected:
  // Iterate all nodes and eliminate identities.
  absl::StatusOr<bool> RunOnFunctionBaseInternal(
      FunctionBase* f, const OptimizationPassOptions& options,
      PassResults* results, OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_IDENTITY_REMOVAL_PASS_H_
