// Copyright 2022 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_PROC_STATE_FSM_PASS_H_
#define XLS_PASSES_PROC_STATE_FSM_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/proc.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Pass which tries to minimize the size and total number of elements of the
// proc state by optimizing implicit state-machines in the state elements.
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// The `ProcStateOptimizationPass` is an optimization pass in XLS that focuses
// on minimizing the size and total number of state elements within a Proc.
// This is a critical optimization for hardware generation, as fewer and smaller
// state elements directly translate to reduced register count and memory usage,
// leading to more compact, faster, and more efficient hardware designs.
//
// **Conversion of Constant Chains to State Machines**:
//
//     This optimization identifies sequences of state elements that effectively
//     form a counter or a simple state machine driven by a constant input. For
//     example, if `next[C[i+1]]` is semantically equivalent to
//     `state_read[C[i]]` and `next[C[0]]` is a constant, this sequence can be
//     converted into a single, compact state machine. Instead of using a
//     one-hot encoding (which `ProcStateArrayFlatteningPass` might produce),
//     this pass converts it into a binary-encoded state machine using
//     `log2(chain_length)` bits, which is more area-efficient. The reads of
//     the original state elements are then replaced by a `select` operation
//     that decodes the state machine's value to produce the corresponding
//     original state element value.
//
// **Benefits**:
//
// *   **Area Reduction**: Directly reduces the number of registers and memory
//     required for state, leading to smaller hardware footprints.
// *   **Power Reduction**: Fewer registers and less active logic contribute to
//     lower power consumption in the synthesized design.
// *   **IR Simplification**: Removes redundant state and associated logic,
//     making the IR cleaner and easier for subsequent compilation stages to
//     process.
class ProcStateFSMPass : public OptimizationProcPass {
 public:
  static constexpr std::string_view kName = "proc_state_fsm";
  ProcStateFSMPass()
      : OptimizationProcPass(kName,
                             "Proc State Finite state machine Optimization") {}
  ~ProcStateFSMPass() override = default;

  RedundancyGuard GetRedundancyGuard(
      const OptimizationPassOptions& options,
      OptimizationContext& context) const override {
    return RedundancyGuard::CanSkip();
  }

 protected:
  absl::StatusOr<bool> RunOnProcInternal(
      Proc* proc, const OptimizationPassOptions& options, PassResults* results,
      OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_PROC_STATE_FSM_PASS_H_
