// Copyright 2020 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_REASSOCIATION_PASS_H_
#define XLS_PASSES_REASSOCIATION_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/function_base.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Reassociates associative operations to reduce delay by transforming chains of
// operations to a balanced tree of operations, and gathering together constants
// in the expression for folding.
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// The `ReassociationPass` is an optimization pass in XLS that reorders
// associative operations such as addition (`add`), subtraction (`sub`), and
// signed/unsigned multiplication (`smul`, `umul`). Its primary objectives are
// to reduce the critical path delay of the synthesized hardware and to
// facilitate further constant folding by grouping literal operands.
//
// This pass is crucial for transforming deep, unbalanced chains of operations
// (e.g., `(((A + B) + C) + D)`) into more balanced tree structures
// (e.g., `((A + B) + (C + D))`). It also effectively gathers together constant
// operands within an associative expression, making them amenable to subsequent
// constant folding optimizations.
//
// **Key Concepts**:
//
// *   **Associativity**: The pass exploits the associative property of
//     operations like addition and multiplication. This property states that
//     for an associative operation `op`, `(A op B) op C` is mathematically
//     equivalent to `A op (B op C)`. Reassociation leverages this to
//     restructure the computation graph.
// *   **Critical Path Delay Reduction**: A deep, unbalanced chain of operations
//     in the IR directly translates to a long critical path in the hardware,
//     which limits the maximum clock frequency. By rebalancing these chains
//     into a shallower tree, the pass effectively reduces the overall critical
//     path delay.
// *   **Constant Folding Facilitation**: Grouping constant operands together
//     within an associative expression allows the `ConstantFoldingPass` to
//     combine them into a single literal. This simplifies the expression and
//     reduces dynamic computation.
// *   **Overflow Handling**: The pass is designed to carefully consider
//     potential overflow conditions, particularly for signed arithmetic and
//     operations involving different bit widths. This ensures that the semantic
//     correctness of the original computation is rigorously preserved during
//     reassociation.
//
// **How it Works**:
//
// 1.  **`AssociativeElements` Class**: This internal helper class is central
//     to the pass's operation. For each node identified as part of an
//     associative chain, it recursively collects and models:
//     *   `variables_`: Non-constant leaf nodes (e.g., parameters or results of
//         other complex expressions).
//     *   `constants_`: Constant leaf nodes (i.e., `literal` operations).
//     *   `op_`: The primary associative operation (`Op::kAdd`, `Op::kSMul`,
//         etc.) governing the combination of these elements.
//     *   `needs_negate`: A boolean flag indicating if a variable needs to be
//         logically negated, typically arising from subtraction operations
//         (e.g., `A - B` is conceptually treated as `A + (-B)`).
//     *   `overflows_`: A flag indicating whether the sub-expression
//         represented by this `AssociativeElements` object can potentially
//         overflow at its current bit-width. This information is crucial for
//         safe combination.
//     *   `depth_`: Tracks the depth of the longest chain of associative
//         operations leading to this particular node.
//
// 2.  **`OneShotReassociationVisitor`**: This visitor traverses the IR in a
//     single pass to compute and collect the `AssociativeElements` for each
//     relevant node. It includes logic to handle various operations:
//     *   **Associative Operations (`Add`, `Sub`, `SMul`, `UMul`)**: For these
//         operations, it recursively combines the `AssociativeElements` of its
//         operands, managing negation for subtraction and tracking potential
//         overflow conditions.
//     *   **`Neg`**: Handles negation by logically flipping the `needs_negate`
//         flag of its operand's `AssociativeElements` representation.
//     *   **Extensions (`ZeroExtend`, `SignExtend`) and `Concat` operations
//         that effectively act as `ZeroExtend`**: These operations can widen a
//         value without fundamentally changing its underlying numerical value.
//         The pass attempts to "see through" these by propagating the
//         `AssociativeElements` of the inner operand if no overflow occurs and
//         signedness compatibility is maintained.
//
// 3.  **`ReassociationCache`**: This caching mechanism stores the computed
//     `AssociativeElements` for each node. This avoids redundant computations
//     during iterative passes and helps ensure that analyses are kept
//     up-to-date even after transformations have altered the graph structure.
//
// 4.  **`Reassociate` Function (Main Loop)**:
//     *   **Fixed-Point Iteration**: The pass operates in a fixed-point manner.
//         It identifies nodes that are prime candidates for reassociation and
//         repeatedly applies the transformation until no further beneficial
//         changes can be made across the entire function.
//     *   **Candidate Selection**: Nodes are selected for reassociation if they
//         meet specific criteria, including:
//         *   Not already a leaf node (i.e., they are part of a larger
//             associative chain).
//         *   Not composed entirely of constants (these are handled by the
//             separate `ConstantFoldingPass`).
//         *   Having users that require materialization (i.e., the
//             reassociation is not trivially hidden by other optimizations).
//         *   Their current depth in the IR graph is greater than the minimum
//             possible depth for a balanced tree of its elements, or they
//             contain multiple constants that can be meaningfully grouped.
//     *   **`ReassociateOneOperation`**: This function is responsible for
//         actually reconstructing the selected associative operation into a
//         balanced tree:
//         *   **Grouping Constants**: It first groups all constant operands
//             together to be combined by `ConstantFoldingPass`.
//         *   **Balancing Tree**: It then constructs a balanced binary tree
//             using the variable elements, minimizing the depth of the overall
//             computation.  The tree is typically biased to the left to ensure
//             a consistent output structure, which can further aid subsequent
//             Common Subexpression Elimination (CSE).
//         *   **Negation and Extension Handling**: It correctly applies
//             necessary negations and extensions (sign-extend/zero-extend)
//             during the reconstruction process to strictly preserve semantic
//             equivalence.
//
// **Benefits**:
//
// *   **Reduced Critical Path**: By transforming deep chains of operations into
//     balanced trees, the pass significantly reduces the critical path delay in
//     the generated hardware, allowing for higher clock frequencies.
// *   **Improved Constant Folding**: Grouping constant operands together within
//     associative expressions enables `ConstantFoldingPass` to reduce them to
//     single literals, thereby simplifying the IR and reducing dynamic
//     computation.
// *   **Enhanced IR Structure**: Creates a more canonical and optimized
//     structure for associative expressions, which can benefit subsequent
//     optimization passes by providing a clearer and more efficient
//     representation of the computation.
//
// Example (Rebalancing additions):
// Consider a deep, left-leaning chain of addition operations:
//
//
// ```
// // Original IR snippet (deep left-leaning chain)
// fn deep_add(a: bits[32], b: bits[32], c: bits[32], d: bits[32]) -> bits[32] {
//   add.1: bits[32] = add(a, b)
//   add.2: bits[32] = add(add.1, c)
//   ret add.3: bits[32] = add(add.2, d)
// }
// ```
//
//
// The `ReassociationPass` would transform this into a balanced tree structure:
//
//
// ```
// // Optimized IR (after ReassociationPass and a subsequent DCE pass)
// fn deep_add(a: bits[32], b: bits[32], c: bits[32], d: bits[32]) -> bits[32] {
//   add.left: bits[32] = add(a, b)
//   add.right: bits[32] = add(c, d)
//   ret add.final: bits[32] = add(add.left, add.right)
// }
// ```
//
// This transformation reduces the maximum depth of the additions from 3 to 2,
// directly improving potential timing performance.
class ReassociationPass : public OptimizationFunctionBasePass {
 public:
  static constexpr std::string_view kName = "reassociation";
  ReassociationPass() : OptimizationFunctionBasePass(kName, "Reassociation") {}
  ~ReassociationPass() override = default;

 protected:
  absl::StatusOr<bool> RunOnFunctionBaseInternal(
      FunctionBase* f, const OptimizationPassOptions& options,
      PassResults* results, OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_REASSOCIATION_PASS_H_
