// Copyright 2023 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_RECEIVE_DEFAULT_VALUE_SIMPLIFICATION_PASS_H_
#define XLS_PASSES_RECEIVE_DEFAULT_VALUE_SIMPLIFICATION_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/proc.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Optimization which removes useless selects between the data value of a
// conditional or non-blocking receive and the default value of the receive (all
// zeros).
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// The `ReceiveDefaultValueSimplificationPass` is an optimization pass tailored
// for Procs in XLS. Its purpose is to identify and eliminate redundant `select`
// or `priority_select` operations that are used to explicitly handle the
// default zero value produced by conditional (`receive_if`) or non-blocking
// (`receive_non_blocking`) receive operations when no data is available.
//
// In XLS, when a conditional or non-blocking receive operation does not
// successfully yield data (either its predicate is false, or it's non-blocking
// and no data is present on the channel), the data output of the `receive`
// operation defaults to an all-zeros value of the appropriate type. It's a
// common pattern to see IR where this default zero behavior is explicitly
// reinforced by a `select` or `priority_select` operation.
//
// The pass targets two primary patterns:
//
// 1.  **Conditional Receive (`receive_if`) Pattern**:
//     If a `receive_if(token, predicate, channel_name)` operation has its data
//     output (`tuple_index(receive_op, 1)`) fed into a `select` operation like
//     `select(predicate, cases=[literal(0), receive_data_output])`, this
//     `select` is redundant. When `predicate` is false, `receive_if` already
//     produces zero data, and the `select` chooses `literal(0)`. When
//     `predicate` is true, `receive_if` produces the actual
//     `receive_data_output`, and the `select` chooses `receive_data_output`.
//     In both cases, the `select` simply passes through the effective
//     `receive_data_output`.
//
// 2.  **Non-Blocking Receive (`receive_non_blocking`) Pattern**:
//     A `receive_non_blocking(token, channel_name)` operation typically
//     returns a tuple `(token, data_output, valid_bit)`. If the `data_output`
//     (`tuple_index(receive_op, 1)`) is subsequently fed into a `select` like
//     `select(valid_bit, cases=[literal(0), receive_data_output])`, this
//     `select` is also redundant. When `valid_bit` is false,
//     `receive_data_output` is implicitly zero, and the `select` chooses
//     `literal(0)`. When `valid_bit` is true, `receive_data_output` is the
//     actual received data, and the `select` chooses `receive_data_output`.
//     Again, the `select` is effectively a passthrough.
//
// The `ReceiveDefaultValueSimplificationPass` identifies these specific
// redundant patterns and replaces the `select` or `priority_select` node
// directly with the actual data output from the `receive` operation, thereby
// eliminating unnecessary logic and simplifying the IR.
//
// Example (Conditional Receive with redundant `select`):
//
//
// ```
// // Original IR snippet
// chan in(bits[32], kind=streaming, ops=receive_only, flow_control=ready_valid)
//
// proc p(pred: bits[1], s: bits[32], init={1, 42}) {
//   tkn: token = literal(value=token)
//   // data is 0 if pred is false
//   receive.1: (token, bits[32]) = receive(tkn, predicate=pred, channel=in)
//   receive_data: bits[32] = tuple_index(receive.1, index=1)
//   // This select is redundant: it effectively always yields 'receive_data'
//   select.2: bits[32] = sel(pred, cases=[literal(0), receive_data])
//   next (pred, select.2)
// }
// ```
//
//
// After `ReceiveDefaultValueSimplificationPass`:
//
//
// ```
// // Optimized IR snippet
// chan in(bits[32], kind=streaming, ops=receive_only, flow_control=ready_valid)
//
// proc p(pred: bits[1], s: bits[32], init={1, 42}) {
//   tkn: token = literal(value=token)
//   receive.1: (token, bits[32]) = receive(tkn, predicate=pred, channel=in)
//   receive_data: bits[32] = tuple_index(receive.1, index=1)
//   // select.2 has been removed; receive_data is used directly
//   next (pred, receive_data)
// }
// ```
//
// This simplification reduces the number of nodes in the IR, contributing to
// smaller and potentially more efficient hardware implementations.
class ReceiveDefaultValueSimplificationPass : public OptimizationProcPass {
 public:
  static constexpr std::string_view kName = "recv_default";

  ReceiveDefaultValueSimplificationPass()
      : OptimizationProcPass(kName, "Receive default value simplification") {}
  ~ReceiveDefaultValueSimplificationPass() override = default;

 protected:
  absl::StatusOr<bool> RunOnProcInternal(
      Proc* proc, const OptimizationPassOptions& options, PassResults* results,
      OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_RECEIVE_DEFAULT_VALUE_SIMPLIFICATION_PASS_H_
