// Copyright 2022 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_TOKEN_DEPENDENCY_PASS_H_
#define XLS_PASSES_TOKEN_DEPENDENCY_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/function_base.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Pass which turns data dependencies between certain effectful operations into
// token dependencies. In particular, transitive data dependencies between
// receives and other effectful ops are turned into token dependencies whenever
// no such token dependency already exists.
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// For example, consider a scenario where a `send` operation uses data produced
// by a `receive` operation, but due to the other logic between the send and
// receive the data produced by the receive is not observable by the send. Other
// passes would be free to remove the data dependency on the send (since the
// data from the receive is irrelevant). This would leave the send and receive
// disconnected so, without an explicit token dependency, the scheduler might
// reorder these, leading to incorrect behavior.
//
//
// ```
// chan test_channel(
//   bits[32], id=0, kind=streaming, ops=send_receive,
//   flow_control=ready_valid)
//
// top proc main(__state: (), init={()}) {
//   __token: token = literal(value=token, id=1000)
//   receive.1: (token, bits[32]) = receive(__token, channel=test_channel)
//   tuple_index.2: token = tuple_index(receive.1, index=0)
//   tuple_index.3: bits[32] = tuple_index(receive.1, index=1)
//   send.4: token = send(__token, tuple_index.3, channel=test_channel)
//   after_all.5: token = after_all(send.4, tuple_index.2)
//   tuple.6: () = tuple()
//   next (tuple.6)
// }
// ```
//
//
// In this example, `send.4` uses `tuple_index.3` which comes from `receive.1`.
// The pass will identify this data dependency and add `tuple_index.2` (the
// token from `receive.1`) as an operand to an `after_all` operation that also
// consumes the token from `send.4`, thus enforcing the order:
//
//
// ```
// after_all.5: token = after_all(send.4, after_all_new.X)
//   // where after_all_new.X is effectively the token from receive.1
// ```
//
//
// This ensures that `receive.1` completes before `send.4` can proceed.
class TokenDependencyPass : public OptimizationFunctionBasePass {
 public:
  static constexpr std::string_view kName = "token_dependency";
  TokenDependencyPass()
      : OptimizationFunctionBasePass(kName,
                                     "Convert data dependencies between "
                                     "effectful operations into token "
                                     "dependencies") {}
  ~TokenDependencyPass() override = default;

 protected:
  absl::StatusOr<bool> RunOnFunctionBaseInternal(
      FunctionBase* f, const OptimizationPassOptions& options,
      PassResults* results, OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_TOKEN_DEPENDENCY_PASS_H_
