// Copyright 2020 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_UNROLL_PASS_H_
#define XLS_PASSES_UNROLL_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/function_base.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// Pass which unrolls counted_for loops. Each iteration of the counted_for
// loop is replaced with an explicit `invoke` operation.
//
// For example, a loop like this:
//
// ```
// fn body(i: bits[4], accum: bits[32], zero: bits[32]) -> bits[32] {
//   zero_ext.3: bits[32] = zero_ext(i, new_bit_count=32)
//   add.4: bits[32] = add(zero_ext.3, accum)
//   ret add.5: bits[32] = add(add.4, zero)
// }
//
// fn unrollable() -> bits[32] {
//   literal.1: bits[32] = literal(value=0)
//   ret counted_for.2: bits[32] = counted_for(literal.1, trip_count=2,
//   stride=2, body=body, invariant_args=[literal.1])
// }
// ```
//
//
// would be transformed into:
//
//
// ```
// invoke.0: bits[32] = invoke(literal(0), literal(0), literal(0),
// to_apply=body)
// invoke.1: bits[32] = invoke(literal(2), invoke.0, literal(0), to_apply=body)
// ret invoke.1
// ```
//
class UnrollPass : public OptimizationFunctionBasePass {
 public:
  static constexpr std::string_view kName = "loop_unroll";
  UnrollPass() : OptimizationFunctionBasePass(kName, "Unroll counted loops") {}

 protected:
  absl::StatusOr<bool> RunOnFunctionBaseInternal(
      FunctionBase* f, const OptimizationPassOptions& options,
      PassResults* results, OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_UNROLL_PASS_H_
