// Copyright 2022 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef XLS_PASSES_USELESS_IO_REMOVAL_PASS_H_
#define XLS_PASSES_USELESS_IO_REMOVAL_PASS_H_

#include <string_view>

#include "absl/status/statusor.h"
#include "xls/ir/package.h"
#include "xls/passes/optimization_pass.h"
#include "xls/passes/pass_base.h"

namespace xls {

// Pass which removes sends/receives that have literal false as their condition.
// Also removes the condition from sends/receives that have literal true as
// their condition.
//
// Note: What follows was generated by the Gemini LLM. Not human verified.
//
// This pass optimizes the IR by eliminating or simplifying I/O operations (send
// and receive) based on their predicate (condition) values. This helps reduce
// dead code and simplify the control flow of the hardware.
//
// Specifically, it handles two main cases:
//
// 1. **Removal of Useless Conditional I/O:** If a `send` or `receive`
//    operation has a predicate that is a literal `false`, and there are other
//    active I/O operations on the same channel, the useless operation is
//    removed. If it's the only remaining I/O operation on that channel, its
//    data input is replaced with a literal zero to avoid leaving the channel
//    unused.
//
//    Example (SendIf with literal false predicate):
//
//    ```
//    send.1: token = send(tkn, data, predicate=literal(value=0))
//    // This send will never execute
//    // ... other operations, potentially another send on the same channel
//    ```
//
//    This `send.1` would be replaced by `tkn` (its token operand), effectively
//    removing the send operation.
//
// 2. **Simplification of Unconditional I/O:** If a `send` or `receive`
//    operation has a predicate that is a literal `true`, the predicate itself
//    is removed.  The operation then becomes an unconditional `send` or
//    `receive`.
//
//    Example (ReceiveIf with literal true predicate):
//
//    ```
//    receive.1: (token, bits[32]) = receive(tkn, predicate=literal(value=1),
//    channel=my_channel)
//    ```
//
//    This `receive.1` would be transformed into:
//
//    ```
//    receive.1: (token, bits[32]) = receive(tkn, channel=my_channel)
//    ```
//
class UselessIORemovalPass : public OptimizationPass {
 public:
  static constexpr std::string_view kName = "useless_io_remove";
  UselessIORemovalPass()
      : OptimizationPass(kName, "Remove useless send/receive") {}
  ~UselessIORemovalPass() override = default;

 protected:
  absl::StatusOr<bool> RunInternal(Package* p,
                                   const OptimizationPassOptions& options,
                                   PassResults* results,
                                   OptimizationContext& context) const override;
};

}  // namespace xls

#endif  // XLS_PASSES_USELESS_IO_REMOVAL_PASS_H_
