# proto-file: xls/contrib/xlscc/hls_block.proto
# proto-message: xlscc.HLSBlock
channels {
  name: "in"
  is_input: true
  type: FIFO
}
channels {
  name: "out"
  is_input: false
  type: FIFO
}
channels {
  name: "memory"
  is_input: false
  type: MEMORY
  width_in_bits: 64
  depth: 1024
}
name: "Delay"
