# proto-file: xls/contrib/xlscc/hls_block.proto
# proto-message: xlscc.HLSBlock

channels {
  name: "in0"
  is_input: true
  type: CHANNEL_TYPE_FIFO
}
channels {
  name: "in1"
  is_input: true
  type: CHANNEL_TYPE_FIFO
}
channels {
  name: "out"
  is_input: false
  type: CHANNEL_TYPE_FIFO
}
name: "Switch"
