# Copyright 2026 The XLS Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Library for testing against golden files in Python.

Golden files are regenerated by running tests with the
--test_update_golden_files and --xls_source_dir flags, e.g. via
xls/dev_tools/rebuild_golden_files.sh.
"""

import difflib
import os
from absl import flags
from absl import logging
from xls.common import runfiles

_UPDATE_GOLDEN = flags.DEFINE_bool(
    'test_update_golden_files',
    False,
    'whether to update golden reference files',
)
_XLS_SOURCE_DIR = flags.DEFINE_string(
    'xls_source_dir',
    '',
    'base path to use to update golden files, note this will cause writes '
    'within the given directory',
)


def expect_equal_to_golden_file(golden_file_path: str, text: str) -> None:
  """Compares text against a golden reference file, updating it if requested.

  Args:
    golden_file_path: Relative runfiles path to the golden file (e.g.,
      'xls/tools/testdata/codegen_main_test__test_foo.vtxt').
    text: Text obtained from the test to compare against golden.
  """
  if _UPDATE_GOLDEN.value:
    assert (
        _XLS_SOURCE_DIR.value
    ), 'Must specify --xls_source_dir with --test_update_golden_files.'
    dirpath, xls = os.path.split(_XLS_SOURCE_DIR.value.rstrip('/'))
    assert xls == 'xls', (
        _XLS_SOURCE_DIR.value,
        'should end with `/xls/` got',
        xls,
    )
    path_to_write: str = os.path.join(dirpath, golden_file_path)
    logging.info('Updating golden file: %s', path_to_write)
    with open(path_to_write, 'w') as f:
      f.write(text)
  else:
    want: str = runfiles.get_contents_as_text(golden_file_path)
    if text != want:
      diff = difflib.unified_diff(
          want.splitlines(keepends=True),
          text.splitlines(keepends=True),
          fromfile=f'golden ({golden_file_path})',
          tofile='actual',
      )
      diff_str = ''.join(diff)
      raise AssertionError(
          f'Result does not match golden file {golden_file_path}:\n\n'
          f'{diff_str}\n'
          'To update golden files, run:\n'
          '  xls/dev_tools/rebuild_golden_files.sh'
      )
