// Copyright 2020 The XLS Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "absl/flags/flag.h"
#include "absl/log/check.h"
#include "absl/status/status.h"
#include "xls/common/exit_status.h"
#include "xls/common/file/filesystem.h"
#include "xls/common/init_xls.h"
#include "xls/common/status/status_macros.h"
#include "xls/eco/ir_patch.pb.h"
#include "xls/eco/patch_ir.h"
#include "xls/ir/function_base.h"
#include "xls/ir/ir_parser.h"
#include "xls/ir/node.h"
#include "xls/ir/package.h"
#include "xls/scheduling/pipeline_schedule.h"
#include "xls/scheduling/pipeline_schedule.pb.h"
#include "xls/scheduling/scheduling_options.h"

static constexpr std::string_view kUsage = R"(patch_ir_main - Apply an IrPatchProto to XLS IR.

Required flags:
  --input_ir_path / -i       Path to the input IR file to patch.
  --input_patch_path / -p    Path to the IrPatchProto generated by ged_main.
  --output_ir_path / -o      Destination for the patched IR.

Optional flags:
  --input_schedule_path / -s Path to a textproto PackageScheduleProto used to
                             constraint the patched IR schedule.

Examples:
  patch_ir_main --input_ir_path=a.ir --input_patch_path=patch.bin --output_ir_path=patched.ir
  patch_ir_main -i a.ir -p patch.bin -o patched.ir -s schedule.textproto
)";

ABSL_FLAG(std::string, input_ir_path, "",
          "Path to the IR file to patch. Short alias: -i.");  // NOLINT
ABSL_FLAG(std::string, input_patch_path, "",
          "Path to the patch file. Short alias: -p.");  // NOLINT
ABSL_FLAG(std::string, output_ir_path, "",
          "Path to the patched IR file. Short alias: -o.");  // NOLINT
ABSL_FLAG(std::optional<std::string>, input_schedule_path, std::nullopt,
          "Path to the schedule file. Short alias: -s.");  // NOLINT

namespace xls {

using PackagePipelineSchedulesProto = PackageScheduleProto;

static absl::StatusOr<PipelineSchedule> PipelineScheduleFromProto(
    FunctionBase* function,
    const PackagePipelineSchedulesProto& package_schedules_proto) {
  // This the modified version of PipelineSchedule::FromProto that ignores
  // extra nodes in the proto.
  const auto schedule_it =
      package_schedules_proto.schedules().find(function->name());
  if (schedule_it == package_schedules_proto.schedules().end()) {
    return absl::InvalidArgumentError("Function does not have a schedule.");
  }
  ScheduleCycleMap cycle_map;
  for (const auto& stage : schedule_it->second.stages()) {
    for (const auto& timed_node : stage.timed_nodes()) {
      // check if function has node
      if (function->GetNode(timed_node.node()).ok()) {
        XLS_ASSIGN_OR_RETURN(Node * node, function->GetNode(timed_node.node()));
        cycle_map[node] = stage.stage();
      }
    }
  }
  std::optional<int64_t> min_clock_period_ps;
  if (schedule_it->second.has_min_clock_period_ps()) {
    min_clock_period_ps = schedule_it->second.min_clock_period_ps();
  }
  return PipelineSchedule(function, cycle_map, /*length=*/std::nullopt,
                          min_clock_period_ps);
}
static absl::Status RealMain(
    const std::string& ir_path, const std::string& patch_path,
    const std::string& output_path,
    const std::optional<std::string>& input_schedule_path) {
  if (ir_path.empty()) {
    return absl::InvalidArgumentError(
        "Missing --input_ir_path flag (-i).");
  }
  if (patch_path.empty()) {
    return absl::InvalidArgumentError(
        "Missing --input_patch_path flag (-p).");
  }
  if (output_path.empty()) {
    return absl::InvalidArgumentError(
        "Missing --output_ir_path flag (-o).");
  }

  XLS_ASSIGN_OR_RETURN(std::string ir_data, GetFileContents(ir_path));
  XLS_ASSIGN_OR_RETURN(std::string patch_data, GetFileContents(patch_path));
  xls_eco::IrPatchProto patch;
  patch.ParseFromString(patch_data);
  XLS_ASSIGN_OR_RETURN(std::unique_ptr<Package> package,
                       Parser::ParsePackage(ir_data));
  FunctionBase* function_base = package->GetTop().value();
  std::optional<PipelineSchedule> schedule;
  PatchIr patch_ir(function_base, patch);
  XLS_RETURN_IF_ERROR(patch_ir.ApplyPatch());
  if (input_schedule_path.has_value()) {
    XLS_ASSIGN_OR_RETURN(
        PackagePipelineSchedulesProto schedule_proto,
        ParseTextProtoFile<PackagePipelineSchedulesProto>(
            input_schedule_path.value()));
    XLS_ASSIGN_OR_RETURN(
        schedule, PipelineScheduleFromProto(function_base, schedule_proto));
    XLS_RETURN_IF_ERROR(patch_ir.PatchSchedule(schedule.value()));
    XLS_RETURN_IF_ERROR(patch_ir.ExportScheduleProto());
  }
  auto output_dir = output_path.substr(0, output_path.find_last_of("/\\"));
  XLS_RETURN_IF_ERROR(!FileExists(output_dir).ok()
                          ? RecursivelyCreateDir(output_dir)
                          : absl::OkStatus());
  XLS_RETURN_IF_ERROR(patch_ir.ExportIr(output_path));
  return absl::OkStatus();
}
}  // namespace xls

namespace {

std::vector<std::string> CanonicalizeArgs(int argc, char* argv[]) {
  const std::vector<std::pair<std::string, std::string>> kShortToLong = {
      {"-i", "--input_ir_path"},
      {"-p", "--input_patch_path"},
      {"-o", "--output_ir_path"},
      {"-s", "--input_schedule_path"},
  };
  std::vector<std::string> canonical;
  canonical.reserve(argc);
  for (int i = 0; i < argc; ++i) {
    canonical.emplace_back(argv[i]);
  }
  for (size_t i = 1; i < canonical.size(); ++i) {
    std::string& arg = canonical[i];
    for (const auto& [short_flag, long_flag] : kShortToLong) {
      if (arg == short_flag) {
        arg = long_flag;
        break;
      }
      std::string prefix = short_flag + std::string("=");
      if (arg.rfind(prefix, 0) == 0) {
        arg = long_flag + "=" + arg.substr(prefix.size());
        break;
      }
    }
  }
  return canonical;
}

}  // namespace

int main(int argc, char** argv) {
  std::vector<std::string> canonical_args = CanonicalizeArgs(argc, argv);
  std::vector<char*> argv_ptrs;
  argv_ptrs.reserve(canonical_args.size());
  for (std::string& arg : canonical_args) {
    argv_ptrs.push_back(arg.data());
  }
  std::vector<std::string_view> positional_args =
      xls::InitXls(kUsage, static_cast<int>(argv_ptrs.size()),
                   argv_ptrs.data());
  return xls::ExitStatus(xls::RealMain(
      absl::GetFlag(FLAGS_input_ir_path), absl::GetFlag(FLAGS_input_patch_path),
      absl::GetFlag(FLAGS_output_ir_path),
      absl::GetFlag(FLAGS_input_schedule_path)));
}
