# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# proto-file: third_party/xls/delay_model/delay_model.proto
# proto-message: xls.delay_model.DelayModel

# Dummy "unit" model for testing. All operations have unit latency (1ps).
op_models { op: "OP_ADD" estimator { fixed: 1 } }
op_models { op: "OP_AND" estimator { fixed: 1 } }
op_models { op: "OP_AND_REDUCE" estimator { fixed: 1 } }
op_models { op: "OP_NAND" estimator { fixed: 1 } }
op_models { op: "OP_NOR" estimator { fixed: 1 } }
op_models { op: "OP_ARRAY" estimator { fixed: 1 } }
op_models { op: "OP_ARRAY_INDEX" estimator { fixed: 1 } }
op_models { op: "OP_ARRAY_UPDATE" estimator { fixed: 1 } }
op_models { op: "OP_BIT_SLICE" estimator { fixed: 1 } }
op_models { op: "OP_CONCAT" estimator { fixed: 1 } }
op_models { op: "OP_DECODE" estimator { fixed: 1 } }
op_models { op: "OP_ENCODE" estimator { fixed: 1 } }
op_models { op: "OP_EQ" estimator { fixed: 1 } }
op_models { op: "OP_IDENTITY" estimator { fixed: 1 } }
op_models { op: "OP_LITERAL" estimator { fixed: 1 } }
op_models { op: "OP_NE" estimator { fixed: 1 } }
op_models { op: "OP_NEG" estimator { fixed: 1 } }
op_models { op: "OP_NOT" estimator { fixed: 1 } }
op_models { op: "OP_ONE_HOT" estimator { fixed: 1 } }
op_models { op: "OP_ONE_HOT_SEL" estimator { fixed: 1 } }
op_models { op: "OP_OR" estimator { fixed: 1 } }
op_models { op: "OP_OR_REDUCE" estimator { fixed: 1 } }
op_models { op: "OP_PARAM" estimator { fixed: 1 } }
op_models { op: "OP_REVERSE" estimator { fixed: 1 } }
op_models { op: "OP_SDIV" estimator { fixed: 1 } }
op_models { op: "OP_SEL" estimator { fixed: 1 } }
op_models { op: "OP_SGE" estimator { fixed: 1 } }
op_models { op: "OP_SGT" estimator { fixed: 1 } }
op_models { op: "OP_SHLL" estimator { fixed: 1 } }
op_models { op: "OP_SHRL" estimator { fixed: 1 } }
op_models { op: "OP_SHRA" estimator { fixed: 1 } }
op_models { op: "OP_SIGN_EXT" estimator { fixed: 1 } }
op_models { op: "OP_SLE" estimator { fixed: 1 } }
op_models { op: "OP_SLT" estimator { fixed: 1 } }
op_models { op: "OP_SMUL" estimator { fixed: 1 } }
op_models { op: "OP_SUB" estimator { fixed: 1 } }
op_models { op: "OP_TUPLE" estimator { fixed: 1 } }
op_models { op: "OP_TUPLE_INDEX" estimator { fixed: 1 } }
op_models { op: "OP_UDIV" estimator { fixed: 1 } }
op_models { op: "OP_UGE" estimator { fixed: 1 } }
op_models { op: "OP_UGT" estimator { fixed: 1 } }
op_models { op: "OP_ULE" estimator { fixed: 1 } }
op_models { op: "OP_ULT" estimator { fixed: 1 } }
op_models { op: "OP_UMUL" estimator { fixed: 1 } }
op_models { op: "OP_XOR" estimator { fixed: 1 } }
op_models { op: "OP_XOR_REDUCE" estimator { fixed: 1 } }
op_models { op: "OP_ZERO_EXT" estimator { fixed: 1 } }
